### ISSUE TITLE
Attempting to modify install paths

### ISSUE THREAD

**Issue by jacklightbody** [unoconv/unoconv#100]
Hi,
I'm trying to use unoconv with just the command line tools of libreoffice on a centos install.The neccessary tools seem to be pyuno.so, soffice.bin, and python (I couldn't find any python-core files). To do this I'm trying to modify the paths to look in to search in the current directory. However, I'm getting an error that the install can't be located. Am I doing something wrong, or is this not currently possible.
my code is
    `extrapaths += glob.glob(os.path.dirname(os.path.realpath(__file__))+'*') + \`
Thanks, Jack

**Comment by regebro** [comment]
It's probably better to install Libreoffice in one of the standard supported ways.
