### ISSUE TITLE
Hybrid PDF output support

### ISSUE THREAD

**Issue by net147** [unoconv/unoconv#115]
It would be great if unoconv could convert an .odt to PDF/ODF hybrid file format as detailed on http://www.libreoffice.org/features/extensions/ so that the .pdf can be easily edited afterwards in LibreOffice.

**Comment by dagwieers** [comment]
I looked into this again, and apart from the option in the GUI, I cannot find an option in the UNO interface to enable Hybrid (ODF Embedded) PDF files.
