### ISSUE TITLE
PDF to HTML Conversion

### ISSUE THREAD

**Issue by shyem** [unoconv/unoconv#123]
I am trying to convert PDF (that was created from Word) to HTML, it converts without any error but the output html file have un-readable characters. I am using Ubuntu server with latest version of LibreOffice and unuconv. is there is special requirements for PDF ?

**Comment by shividhar** [comment]
+1 Problem persists.

**Comment by Lewiscowles1986** [comment]
has anyone tried pdf -> odt, then odt ->html?

**Comment by alivx** [comment]
Same issue
`root@e16ff9529939:/app/app/media-convert# unoconv -f odt 2.pdf
root@e16ff9529939:/app/app/media-convert# unoconv -f html 2.odt 
Traceback (most recent call last):
  File "/usr/bin/unoconv", line 1037, in convert
    document.storeToURL(outputurl, tuple(outputprops) )
uno.IOException: SfxBaseModel::impl_store <file:///app/app/media-convert/2.html> failed: 0xc10(Error Area:Io Class:Write Code:16)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/unoconv", line 1282, in <module>
    main()
  File "/usr/bin/unoconv", line 1198, in main
    convertor.convert(inputfn)
  File "/usr/bin/unoconv", line 1039, in convert
    raise UnoException("Unable to store document to %s (ErrCode %d)\n\nProperties: %s" % (outputurl, e.ErrCode, outputprops), None)
  File "/usr/lib/python3/dist-packages/uno.py", line 516, in _uno_struct__getattr__
    return getattr(self.__dict__["value"], name)
AttributeError: ErrCode
`

**Comment by Lewiscowles1986** [comment]
Looks like write permissions. Weird thing is that I'm not 100% certain it should be making such a URL. Are you calling with a url specifier to a file, or a standard path for your OS?

**Comment by regebro** [comment]
@alivx That is not the same issue. I agree it could be permissions.

**Comment by regebro** [comment]
As for the main issue, I think it depends on the PDF. PDF's are essentially a graphical format, and not all PDF's have extractable text.
