### ISSUE TITLE
Source file cannot be read. Unsupported URL

### ISSUE THREAD

**Issue by adityar7** [unoconv/unoconv#129]
I'm trying to run unoconv to convert documents remotely.

If I run both the listener and the client on the same machine, everything works fine. However, if I run the listener of a different machine then I get the following error:

```
$ unoconv -s 192.168.1.11 -p 2002 -n -vvv test.doc 
Verbosity set to level 3
Using office base path: /Applications/LibreOffice.app/Contents
Using office binary path: /Applications/LibreOffice.app/Contents/MacOS
DEBUG: Connection type: socket,host=192.168.1.11,port=2002;urp;StarOffice.ComponentContext
Input file: test.doc
UNO IllegalArgument during import phase:
Source file cannot be read. Unsupported URL <file:///Users/abc/test.doc>: ""
```

The listener is run like so.

```
$ ./unoconv --listener -s 192.168.1.11 -p 2002 -vvv
Verbosity set to level 3
Using office base path: /Applications/LibreOffice.app/Contents
Using office binary path: /Applications/LibreOffice.app/Contents/MacOS
Start listener on 192.168.1.11:2002
```

I have tried several versions of LibreOffice in the 3.5 and 3.6 families as well as with several different documents and always run into this issue. I am running the `master` branch of unoconv. Both machines are Mac OS X 10.7 but I have tried Ubuntu as well. There is no firewall and the file permissions are 777.

Any idea what could be going on?

As a last resort I'll have to wrap the listener inside my own tcp service script, but the in-built service would be ideal.

**Comment by dagwieers** [comment]
Thanks for the feedback.
Not sure what I can do about this though :-/
