### ISSUE TITLE
unoconv freezes randomly

### ISSUE THREAD

**Issue by ghost** [unoconv/unoconv#130]
Dear Dag,

thank you for this really useful tool which is unoconv. I am using it for several weeks and it already helped me to convert thousand of documents.

However, sometimes conversions freeze randomly. When that happens, the only solution is to kill all the conversion processes and to restart the listeners.

Moreover, my soffice.bin process seems to terminate regularly without explanation (average : every 5-6 hours).

Maybe you know why... I am using unoconv v1.5, on a Debian system 64 bits (Wheezy version).

**Comment by swaathi** [comment]
Hi Dag, 

I'm running Unoconv 0.6, and I am running into the same issue. Sometimes Unoconv just freezes up. I was forced to kill the process, and this is the error it spit out,

``` ^CTraceback (most recent call last):
  File "/usr/local/bin/unoconv", line 721, in __init__
    unocontext = resolver.resolve("uno:%s" % op.connection)
uno.NoConnectException: Connector : couldn't connect to socket (Undefined error: 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/unoconv", line 1169, in <module>
    main()
  File "/usr/local/bin/unoconv", line 1086, in main
    convertor = Convertor()
  File "/usr/local/bin/unoconv", line 748, in __init__
    unocontext = resolver.resolve("uno:%s" % op.connection)
SystemError: Couldn't instantiate python representation of structered UNO type com.sun.star.connection.NoConnectException
IRB::Abort: abort then interrupt!
```

I'm not sure whats wrong here. I tried to convert a ppt file to pdf.

**Comment by nkilaru213** [comment]
did you find any solution for this?

**Comment by tommylees112** [comment]
Similar problem:

```
^CTraceback (most recent call last):
  File "/usr/local/bin/unoconv", line 807, in connect
    unocontext = resolver.resolve("uno:%s" % op.connection)
uno.NoConnectException: Connector : couldn't connect to socket (Undefined error: 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/usr/local/bin/unoconv", line 1389, in <module>
    main()
  File "/usr/local/bin/unoconv", line 1303, in main
    convertor = Convertor()
  File "/usr/local/bin/unoconv", line 786, in __init__
    unocontext = self.connect(resolver)
  File "/usr/local/bin/unoconv", line 840, in connect
    unocontext = resolver.resolve("uno:%s" % op.connection)
SystemError: Couldn't instantiate python representation of structered UNO type com.sun.star.connection.NoConnectException
```
Version:
```
unoconv 0.8.2
Written by Dag Wieers <dag@wieers.com>
Homepage at http://dag.wieers.com/home-made/unoconv/

platform posix/darwin
python 3.3.5 (default, Jul 25 2014, 02:41:25) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]
LibreOffice 4.3.0.4
```

**Comment by RodrigoPetter** [comment]
Same problem here. This is probably a problem with the LibreOffice and not with unoconv. Here at my office users use LibreOffice and it also randomly freezes (windows).

**Comment by mbardelmeijer** [comment]
Same problem, anyone found a workaround for this?

**Comment by thilux** [comment]
Same problem here, using the latest version from the master branch.

unoconv 0.8.2
Written by Dag Wieers <dag@wieers.com>
Homepage at http://dag.wieers.com/home-made/unoconv/

platform posix/linux
python 3.6.8 (default, Apr  8 2019, 18:17:52)
[GCC 8.3.0]
LibreOffice 6.1.4.2

Scenario:

- I am running a unoconv listener and having 10 simultaneous users make requests using unoconv using the port of the listener. It goes pretty well, but when I reach the 8th round of each user, it gets stuck. If I add additional users, though, they still can process (always using the single listener) just fine.

Can this be reopened?

**Comment by RodrigoPetter** [comment]
This is a LibreOffice problem. The process that freezes is from LibreOffice not Unoconv.

The same thing happens periodically using LibreOffice without Unoconv.

I've done a workaround using multiple Docker containers. Using the HealthCheck provided by docker, I periodically try to convert a file to PDF. If the process gets stuck the docker itself restarts the Unoconv container.

I'm already using Docker (in swarm mode) in my stack. I would not recommend this workaround if you don't have docker in your environment.

We have about 1200 users using unoconv to convert .odt files and images to PDF. Unoconv freezes at least five times a week.
