### ISSUE TITLE
unoconv: Cannot find suitable office installation on your system. - Windows

### ISSUE THREAD

**Issue by alexeySTP** [unoconv/unoconv#143]
Hello Dag,

Old question of Windows user:
unoconv: Cannot find suitable office installation on your system.
Error appears on running any command containing python unoconv from cmd.
Windows 2012 Server Standard x64, LibreOffice 3.5-3.6 (tried couple of versions), installed in C:\Program Files (x86)\LibreOffice 3.x (depending upon version).
unoconv 0.6 in C:\Program Files (x86)\LibreOffice 3.x\program (depending upon version).
UNO_PATH =  C:\Program Files (x86)\LibreOffice 3.x\program(depending upon version).
Just in case C:\Program Files (x86)\LibreOffice 3.x\program is in system PATH.
How to fix this pushing unoconv to run?

**Comment by regebro** [comment]
Duplicates #49
