### ISSUE TITLE
unoconv: UnoException during export phase: Unable to store document to file:///home/.../logo.pdf (ErrCode 2074)

### ISSUE THREAD

**Issue by sTb1337** [unoconv/unoconv#164]
Hello everyone, ill get the error 2074:

/Downloads$  ll

-rw-rw-r-- 1 quickstart quickstart     11395 Aug 12 01:09 Screenshot from 2013-08-12 01_08_11.png

~/Downloads$ unoconv -vvv -f pdf -p 8100 -o "/home/quickstart/Downloads/" "/home/quickstart/Downloads/Screenshot from 2013-08-12 01_08_11.png" 
Verbosity set to level 3
Using office base path: /usr/lib/libreoffice
Using office binary path: /usr/lib/libreoffice/program
DEBUG: Connection type: socket,host=127.0.0.1,port=8100;urp;StarOffice.ComponentContext
Input file: /home/quickstart/Downloads/Screenshot from 2013-08-12 01_08_11.png
Selected output format: Portable Document Format [.pdf]
Selected office filter: draw_pdf_Export
Used doctype: graphics
Output file: /home/quickstart/Downloads/Screenshot from 2013-08-12 01_08_11.pdf
unoconv: UnoException during export phase:
Unable to store document to file:///home/quickstart/Downloads/Screenshot%20from%202013-08-12%2001_08_11.pdf (ErrCode 2074)

Properties: ((com.sun.star.beans.PropertyValue){ Name = (string)"FilterName", Handle = (long)0x0, Value = (any){ (string)"draw_pdf_Export" }, State = (com.sun.star.beans.PropertyState)DIRECT_VALUE }, (com.sun.star.beans.PropertyValue){ Name = (string)"OutputStream", Handle = (long)0x0, Value = (any){ (com.sun.star.uno.XInterface)0x9825314{, supportedInterfaces={com.sun.star.lang.XTypeProvider,com.sun.star.io.XOutputStream}} }, State = (com.sun.star.beans.PropertyState)DIRECT_VALUE }, (com.sun.star.beans.PropertyValue){ Name = (string)"Overwrite", Handle = (long)0x0, Value = (any){ (boolean)true }, State = (com.sun.star.beans.PropertyState)DIRECT_VALUE })

~/Downloads$ ps -e | grep soff*
    3 ?        00:00:04 ksoftirqd/0
   10 ?        00:00:05 ksoftirqd/1
23579 pts/4    00:00:01 soffice.bin

 ~/Downloads$ unoconv --version
unoconv 0.6
Written by Dag Wieers dag@wieers.com
Homepage at http://dag.wieers.com/home-made/unoconv/

platform posix/linux2
python 2.7.3 (default, Aug  1 2012, 05:16:07) 
[GCC 4.6.3]
LibreOffice 3.5

**Comment by dagwieers** [comment]
Ok, just as a reference, ErrCode 2074 means:

Binary: 000:01000:00011010
 - Area: 0 (ERRCODE_AREA_TOOLS)
 - Class: 8 (ERRCODE_CLASS_PARAMETER)
 - Code: 26 (ERRCODE_IO_INVALIDPARAMETER)

So not a permission problem, but I assume it has a problem with parsing/using the URL ?

**Comment by nguyen-lh** [comment]
I'm getting these same error messages but when I run the command with -vvv I don't get an error code. @SteffenBxyz have you found a solution? I couldn't even convert a text file I created like you did.

**Comment by sk31337** [comment]
Closed, because
