### ISSUE TITLE
uno bridge removed on ubuntu 13.10 (ErrCode 283)

### ISSUE THREAD

**Issue by roozgar** [unoconv/unoconv#182]
at ubuntu 13.10 the uno has been removed and uses the python3-uno
and the script dont working

peiman@digidoc:/var/www/dg2/docs/1391731200/PUQNFGD$ unoconv -f pdf -o resume.pdf 55bccbd93383e00639e8b8a9ae20a304.doc
unoconv: UnoException during export phase:
Unable to store document to file:///var/www/dg2/docs/1391731200/PUQNFGD/resume.pdf (ErrCode 283)

Properties: ((com.sun.star.beans.PropertyValue){ Name = (string)"FilterName", Handle = (long)0x0, Value = (any){ (string)"writer_pdf_Export" }, State = (com.sun.star.beans.PropertyState)DIRECT_VALUE }, (com.sun.star.beans.PropertyValue){ Name = (string)"Overwrite", Handle = (long)0x0, Value = (any){ (boolean)true }, State = (com.sun.star.beans.PropertyState)DIRECT_VALUE }, (com.sun.star.beans.PropertyValue){ Name = (string)"OutputStream", Handle = (long)0x0, Value = (any){ (com.sun.star.uno.XInterface)0x21f6ee8{, supportedInterfaces={com.sun.star.lang.XTypeProvider,com.sun.star.io.XOutputStream}} }, State = (com.sun.star.beans.PropertyState)DIRECT_VALUE })

is there any way to fix this!?

**Comment by dagwieers** [comment]
Just as a reference, ErrCode 283 means:

Binary: 000:00001:00011011
 - Area: 0 (ERRCODE_AREA_TOOLS)
 - Class: 1 (ERRCODE_CLASS_ABORT)
 - Code: 27 (ERRCODE_IO_ABORT)
