### ISSUE TITLE
swf output

### ISSUE THREAD

**Issue by roozgar** [unoconv/unoconv#184]
im working now with the unoconv
i can get out put of text and pdf but the swf out put size is 0

peiman@digidoc:/var/www/dg2/bin$ python3 unoconv -f txt -o /var/www/dg2/bin/ ../docs/1391731200/UASWVWV/acdcafdc51a7bfbdb67970cb3dd1e002.docx
peiman@digidoc:/var/www/dg2/bin$ python3 unoconv -f swf -o /var/www/dg2/bin/ ../docs/1391731200/UASWVWV/acdcafdc51a7bfbdb67970cb3dd1e002.docx
peiman@digidoc:/var/www/dg2/bin$ ls -l
total 188
-rw-rw-r-- 1 peiman   peiman   35246 Feb 11 07:56 55bccbd93383e00639e8b8a9ae20a304.pdf
-rw-rw-r-- 1 peiman   peiman   56050 Feb 11 07:57 acdcafdc51a7bfbdb67970cb3dd1e002.pdf
-rw-rw-r-- 1 peiman   peiman       0 Feb 11 07:58 acdcafdc51a7bfbdb67970cb3dd1e002.swf
-rw-rw-r-- 1 peiman   peiman   20825 Feb 11 07:58 acdcafdc51a7bfbdb67970cb3dd1e002.txt

is it required to install any package to swf out put!?

UPDATE:
i run the command like this:
 python3 unoconv -f swf -o /var/www/dg2/bin/ ../docs/1391731200/UASWVWV/acdcafdc51a7bfbdb67970cb3dd1e002.docx

**Comment by dagwieers** [comment]
Sorry for not getting back to you any sooner.

And to be honest, I don't know. You can try the [Troubleshooting instructions](https://github.com/dagwieers/unoconv#troubleshooting-instructions) and see if this a general issue with LibreOffice (or with of your distribution). Or ask the LibreOffice project instead.

BTW I can confirm that I have the exact same issue with the latest unoconv and LibreOffice 5.0 (and I do have all the packages installed). So I would ask the LibreOffice project :-)

```bash
[dag@moria unoconv]$ /opt/libreoffice5.0/program/python unoconv -v -f swf cicciò.fodt 
Input file: cicciò.fodt
Selected output format: Macromedia Flash (SWF) [.swf]
Output file: file:///home/dag/home-made/unoconv/cicci%C3%B2.swf
[dag@moria unoconv]$ ls -la cic
cicciò.fodt  cicciò.pdf   cicciò.swf   
[dag@moria unoconv]$ ls -la cicciò.swf 
-rw-rw-r--. 1 dag dag 0 Jul  5 13:56 cicciò.swf
```

**Comment by dagwieers** [comment]
Unfortunately it does work well from the LibreOffice GUI, but I noticed you cannot simply convert any document into a SWF file, you can do it from a PDF file and that does work ! But it does not work from a DOC or ODF document.

So unoconv works exactly as LibreOffice in that regard, only unoconv does not know which formats are coupled like this :-( And I honestly don't know why UNO let it create an empty file instead.

This needs someone to investigate...
