### ISSUE TITLE
Allow conversion to CSV for all sheets in a spreadsheet file 

### ISSUE THREAD

**Issue by ptsefton** [unoconv/unoconv#198]
When you convert a spreadsheet to csv you only get the first worksheet. 

I can't find an issue for this here, although it has been [discussed elsewhere](http://listarc.com/showthread.php?3157968-Unoconv%3A+ODS-%3ECSV+for+all+sheets)  and there seems to be [demand](http://stackoverflow.com/questions/18187656/unoconv-convert-first-sheet-only) for an export that gives all the sheets.

I have implemented a solution, creating this issue so I can do a pull request against it.

**Comment by trufanov-nok** [comment]
I've just faced with this problem. Is there a big problem with implementation of this enhancement?

**Comment by dagwieers** [comment]
No, it is a matter of priorities. I haven't been able to keep up with the issues and pull requests of unoconv, but I am getting there. I propose this functionality for v0.8 because I think this belongs together with the plugin/extension system that we plan to add (which could cover this functionality as well).

**Comment by LuisBL** [comment]
+1

**Comment by stefanrueger** [comment]
I propose simple options that allow one to select the sheet at the very least:
  --sheetname=name
   --sheetnumber=number
See attached unoconv, where I have added this functionality.

[unoconv.txt](https://github.com/dagwieers/unoconv/files/752477/unoconv.txt)

**Comment by cedr-x** [comment]
Thank you @stefanrueger ! you save me hours ;)

**Comment by cedr-x** [comment]
those options sheetname / sheetnumber should be merged to unoconv

**Comment by tonyski** [comment]
@stefanrueger  Great!
But this script is not work with the conversion to PDF,
How can I change this script to make it work?
thanks!

**Comment by amigalemming** [comment]
Will the `--sheetname` and `--sheetnumber` options eventually appear in an official LibreOffice release?

**Comment by anarcat** [comment]
this was closed here, but was it fixed? if so, how? :)

**Comment by Kagee** [comment]
I do not know, but if you **can** use libreoffice headless, you can do something like this
`libreoffice --convert-to "csv:Text - txt - csv (StarCalc):44,34,76,0,,0,true,true,true,false,,2" "File.ods"`
This will create `File-NameOfSheet2.csv`. 

See [filters](https://help.libreoffice.org/latest/ro/text/shared/guide/convertfilters.html) and [CSV Parameters](https://help.libreoffice.org/latest/ro/text/shared/guide/csv_params.html). Be aware that some of these parameters only do something if you *import* csv.

**Comment by anarcat** [comment]
i have this in my `.gitconfig`:

```
# if that doesn't work, consider headless libreoffice, gnumeric, or
# xslx2csv (https://github.com/dilshod/xlsx2csv, not packaged in
# Debian
[diff "xlsx"]
        textconv = libreoffice-cat
```

and `libreoffice-cat` is similar to what you did there, in spirit:

https://gitlab.com/anarcat/scripts/-/blob/main/libreoffice-cat

... alongside dumping stuff in a directory because it will generate multiple pages, one for each sheet...
