### ISSUE TITLE
Integrate with FilterFactory for filter details

### ISSUE THREAD

**Issue by dagwieers** [unoconv/unoconv#20]
Instead of integrating a static list of filters, we definitely should using the FilterFactory service to query the available filters and extensions. The office instance knows best what filters can do, and some filters come and go.

**Comment by dagwieers** [comment]
For an example on how to get the list of filters/formats from LibreOffice, check out this code:
http://svn.erp5.org/erp5/trunk/utils/cloudooo.handler/ooo/cloudooo/handler/ooo/

**Comment by regebro** [comment]
I can't find a way to get any sort of doctype information out of LibreOffice, so this doesn't seem doable unless we refactory unoconv to not support a --doctype argument.

**Comment by regebro** [comment]
Well, I found it, and it's implemented in the Unoserver successor. Unoconv is now in pure bugfix mode.

https://github.com/unoconv/unoserver
