### ISSUE TITLE
Problem with asian font

### ISSUE THREAD

**Issue by bguillonEURISIS** [unoconv/unoconv#214]
Hello, 
I use Unoconv to convert OpenOffice Document to PDF.
My Document contains characters in asian font.
The PDF repaces these characters by '?'.

How can I solve this problem ?
Thanks

**Comment by dagwieers** [comment]
Maybe it helps if we have access to the document, or similar document that reproduces the problem.

**Comment by abdrmdn** [comment]
You want to install those fonts

`
# Adding fonts to support [arabic/asian/msfonts]
Apk --no-cache add msttcorefonts-installer  fontconfig   font-ipa wqy-zenhei
update-ms-fonts

fc-cache -fv
`
or get them using ur Distro package manager.

**Comment by mrhery** [comment]
> 
> 
> You want to install those fonts
> 
> ```
> # Adding fonts to support [arabic/asian/msfonts]
> Apk --no-cache add msttcorefonts-installer  fontconfig   font-ipa wqy-zenhei
> update-ms-fonts
> 
> fc-cache -fv
> ```
> 
> or get them using ur Distro package manager.

What do you mean by install the font?

I have run few command on my Debian 9 terminal:
```
>apt-get install ttf-kacst
>apt-get install ttf-sil-scheherazade
>apt-get install ttf-arabeyes
```

These packages are for Arabic font I took it from https://help.ubuntu.com/community/Fonts

And I match my font setting in my word document (from windows) to match either three of those fonts, and try run `unoconv --output ...` on my Debian 9 server, it still cannot read the font correctly, it return [][][][] and ???? character. 

Are there any other ways to correctly **install** the font? In my case, I am using Debian 9.

**Comment by abdrmdn** [comment]
@mrhery : I vaguely remember this. but, what I do remember is that most of the times installing msttcorefonts (microsoft fonts) usually fixes most of the issues. (try to [look it up here maybe](https://www.marksanborn.net/linux/installing-microsoft-fonts-msttcorefonts-on-debian-linux/)).
As for other chars, lets say Chinese/Korean/Asian. you need to install the `wqy-zenhei` package. 
and by installing I mean either downloading the fonts through a website and putting them in the  right folder, then running the font caching tool to re-index all existing fonts for the system (using `fc-cache -fv`) 
or just by installing them through your package manager. (apk in my case, dpkg in your case for Debian 9).
