### ISSUE TITLE
Libreoffice GraphicImport error

### ISSUE THREAD

**Issue by pgolomysov** [unoconv/unoconv#234]
Just for information.

If you have this error like this: 
/tmp/buildd/libreoffice-3.5.4+dfsg2/writerfilter/source/dmapper/GraphicImport.cxx:1486 failed. Message :GraphicCrop

Just wait and it will be correctly converted (but you get a lot errors).

**Comment by kmgawande** [comment]
Hi guys,

Im getting this error and the PDF is not generating!

Any thoughts?

**Comment by kmgawande** [comment]
Well, the PDF does get created .. just that it takes some time...
Thanks anyways!
