### ISSUE TITLE
use unoconv as a library

### ISSUE THREAD

**Issue by danmilon** [unoconv/unoconv#238]
Is there a way to use unoconv as a library from a python script? Either in a standalone manner or as a client to an already running unoconv server.

Essentially what I'd like to do is convert some documents on demand, but I'd like to avoid spawning processes. If the listener is running I'd like to talk to it and get the result back in python, not a file.

I hope I didn't overcomplicate my question!
Thank you!

**Comment by nagyv** [comment]
From the way unoconv is currently set up, it's not possible. 

You might want to try writing a simple setup.py around unoconv. This would allow it to be registered on pip, and add change the main file name to unoconv.py, but still provide the unoconv command as an entry point. Changing the filename to unoconv.py and have it installed in your PYTHONPATH will allow you to import it, and then you can use it from scripts as you prefer.

**Comment by danmilon** [comment]
Okay, Thank you for the information.
Feel free to close this issue if you feel like.

**Comment by btimby** [comment]
Sorry for the necropost. I just thought I would chime in with an example of doing this. The method I use does not require any changes to `unoconv` proper. I am using this in a threaded context and it is stable.

https://github.com/btimby/preview-server/blob/master/preview/backends/office.py#L20

In a nutshell, it does some import trickery to get a "private" copy of the unoconv CLI tool as a module. Then it performs the work of the `__main__` section and `main()` function to initialize all the (now "private") globals. Finally a `Convertor` instance is returned, which can be used to convert a single file.

@dagwieers Thanks for unoconv, in my testing it is very stable and was able to convert 10,000 documents where my emulation of it failed on 1/10th of them.
