### ISSUE TITLE
Release new versions on PIP

### ISSUE THREAD

**Issue by danmilon** [unoconv/unoconv#239]
Can you please release a new version? I'm particularly interested on the fix for #156.

Thank you!

**Comment by danmilon** [comment]
Silly me! This package is not on PIP.
How do releases work? I'm on ubuntu.

**Comment by nagyv** [comment]
You can easily use the most recent version. 

e.g. what I did:
1. install unoconv using ubuntu's package manager -> I made this step only to get all the required packages installed for me
2. download the most recent version from here
3. launch the downloaded version using something like

```
python3 ~/repos/unoconv/unoconv
```

**Comment by danmilon** [comment]
mhm.. Thats an option. Thank you.
Feel free to close this issue if you feel like.

**Comment by dagwieers** [comment]
Maybe we should be doing PIP releases as well. But currently `unoconv` is very limited as a library.
