### ISSUE TITLE
UnoException during import phase

### ISSUE THREAD

**Issue by wftl** [unoconv/unoconv#25]
Hello Dag,

I'm a bit confused by this one. The listener is running and things start up okay, but as you can see . . . 

./unoconv -f odt -vvvv ./myTestFile.doc 
Verbosity set to level 3
Connection type: socket,host=localhost,port=2002;urp;StarOffice.ComponentContext
Office base location: /usr/lib/libreoffice
Office binary location: /usr/lib/libreoffice/basis-link/program
Input file: ./myTestFile.doc
unoconv: UnoException during import phase in <class '__main__.com.sun.star.lang.IllegalArgumentException'>

I am using the latest github unoconv (from today) and LibreOffice 3.4.4 on Ubuntu 11.10 Oneiric.

Thanks for any help you can offer on this one.
## 

Marcel Gagné
Writer and Free Thinker at Large
Note: This massagee wos nat speel or gramer-checkered.

**Comment by NoumanDilshad** [comment]
I am having this issue while converting all the files other then docx. docx file is converting fine. But other then that, All other office files (xls,xlxs,ppt,pptx) have this issue.
```
unoconv: UnoException during import phase:
The document 'file:///app/uploads/xlsfile.xls' could not be opened.
```
