### ISSUE TITLE
PDF to HTML (ErrCode 3088)

### ISSUE THREAD

**Issue by coltonoscopy** [unoconv/unoconv#279]
Hey guys, having an issue converting a PDF to HTML; here is the error message:

``` bash
jharvard@appliance (~/office_test/pdf): unoconv -f html pdf_test.pdf
unoconv: UnoException during export phase:
Unable to store document to file:///home/jharvard/office_test/pdf/pdf_test.html (ErrCode 3088)

Properties: ((com.sun.star.beans.PropertyValue){ Name = (string)"OutputStream", Handle = (long)0x0, Value = (any){ (com.sun.star.uno.XInterface)0x961a174{, supportedInterfaces={com.sun.star.lang.XTypeProvider,com.sun.star.io.XOutputStream}} }, State = (com.sun.star.beans.PropertyState)DIRECT_VALUE }, (com.sun.star.beans.PropertyValue){ Name = (string)"Overwrite", Handle = (long)0x0, Value = (any){ (boolean)true }, State = (com.sun.star.beans.PropertyState)DIRECT_VALUE }, (com.sun.star.beans.PropertyValue){ Name = (string)"FilterName", Handle = (long)0x0, Value = (any){ (string)"HTML (StarWriter)" }, State = (com.sun.star.beans.PropertyState)DIRECT_VALUE })
```

I've tried looking at other issues that reference this error code and talk about permissions issues, but I'm running everything as sudo, which would prevent that from being an issue right?

**Comment by ribbles** [comment]
Was able to reproduce the issue converting the following document:
[Android-Lollipop-Quick-Start-Guide.pdf](https://static.googleusercontent.com/media/www.google.com/en/us/help/hc/images/android/android_ug_50/Android-Lollipop-Quick-Start-Guide.pdf)

```
unoconv: UnoException during export phase:
Unable to store document to file:///C:/Android-Lollipop-Quick-Start-Guide.html (ErrCode 3088)

Properties: ((com.sun.star.beans.PropertyValue){ Name = (string)"Overwrite", Handle = (long)0x0, Value = (any){ (boolean)true }, State = (com.sun.star.beans.PropertyState)DIRECT_VALUE }, (com.sun.star.beans.PropertyValue){ Name = (string)"FilterName", Handle = (long)0x0, Value = (any){ (string)"HTML (StarWriter)" }, State = (com.sun.star.beans.PropertyState)DIRECT_VALUE }, (com.sun.star.beans.PropertyValue){ Name = (string)"OutputStream", Handle = (long)0x0, Value = (any){ (com.sun.star.uno.XInt
erface)0x3986674{, supportedInterfaces={com.sun.star.io.XOutputStream,com.sun.star.lang.XTypeProvider}} }, State = (com.sun.star.beans.PropertyState)DIRECT_VALUE })
```

**Comment by rahilwazir** [comment]
Same issue

**Comment by dagwieers** [comment]
Just as a reference, ErrCode 3088 means:

Binary: 000:01100:00010000

Area: 0 (ERRCODE_AREA_TOOLS)
Class: 12 (ERRCODE_CLASS_WRITE)
Code: 16 (ERRCODE_IO_CANTWRITE)

So that seems to indicate a permission/ACL/SELinux issue ?

**Comment by rahilwazir** [comment]
But this occurs for only `-f html` formats.

**Comment by anthony-maudry** [comment]
Hello,

Same issue there : 

I ran the command :

```
$ unoconv  --format=html --output=/tmp/unoconv_c2f599841f21aaefeeabd2a60ef7bfe8.html file.xlsx

```

And got the output :

```
unoconv: UnoException during export phase:
Unable to store document to file:///tmp/unoconv_c2f599841f21aaefeeabd2a60ef7bfe8.html (ErrCode 3088)

....
```

Tried to change the format from html to csv :

```
$ unoconv  --format=csv --output=/tmp/unoconv_c2f599841f21aaefeeabd2a60ef7bfe8.html file.xlsx

```
And it worked.

Reproduced as root, myself and www-data (over php script) and got the exactly same result.

Seems that something else than pure access rights on output file is involved here.

All those commands were ran without a server listening.

With a server listening (througt unoconv -l ) got : 

```
unoconv: RuntimeException during import phase: Office probably died. Unsupported URL </tmp/unoconv_c2f599841f21aaefeeabd2a60ef7bfe8>: "from LoadEnv::initializeLoading"

```

Last detail : works fine with some files, not with others... And does not seem to depend on extension or docment type

Any clue ?

**Comment by pquentin** [comment]
Just to make things clear, do you have the same issue when doing this through LibreOffice UI?

**Comment by anthony-maudry** [comment]
As i'm running on a server without X (debian), will be difficult to reproduce in the same conditions.

Anyway on my PC (Windows) I can open and export the file withour any problem with LibreOffice.

**Comment by bkleef** [comment]
Any update on this? Same here with latest `unoconv` (from master branch):

```
unoconv 0.7
Written by Dag Wieers <dag@wieers.com>
Homepage at http://dag.wieers.com/home-made/unoconv/
platform posix/linux
python 3.5.2 (default, Nov  3 2016, 13:17:19)
[GCC 5.3.0]
LibreOffice 5.1.4.2
```

**Comment by bkleef** [comment]
```

**Comment by The-Loeki** [comment]
https://lists.freedesktop.org/archives/libreoffice-bugs/2015-March/263092.html

**Comment by The-Loeki** [comment]
http://docs.libreoffice.org/sfx2/html/sfxbasemodel_8cxx_source.html#l03102

**Comment by bkleef** [comment]
@dagwieers can you please point us in the right direction? I've tried with 10 different Dockerfiles (https://gist.github.com/bkleef/8651eb4b596334c76c839217b5186b1b) and **only** the ones based on Ubuntu write a file but with really strange content: https://gist.github.com/bkleef/246aa1639744ccb133a97976febbe052. I think it has to do with some PDF rendering/processing. Thanks a lot for your time!

**Comment by bhagwats** [comment]
Same issue with libraoffice 5.3.3.2
++++++++++++++++++++
[root@localhost html]# unoconv --version
unoconv 0.7
Written by Dag Wieers <dag@wieers.com>
Homepage at http://dag.wieers.com/home-made/unoconv/

platform posix/linux
python 3.5.3 (default, May  4 2017, 01:06:08) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)]
LibreOffice 5.3.3.2

**Comment by regebro** [comment]
I can confirm that this is an issue, but I can also confirm that Libreoffice will open and treat PDFs like they are images, and that the resulting HTML export from Libreoffice is horrid and ugly, so I'm pretty sure this is not what you want to do. I'm keeping it open for the time being, but really, don't convert PDF's to HTML, at least not with Libreoffice.
