### ISSUE TITLE
Feature request: replace cross-references/index with text

### ISSUE THREAD

**Issue by ghost** [unoconv/unoconv#304]
It would be great if cross-references and table of contents, etc. could optionally be replaced with their txt when converting from, e.g. odt -> docx. I've sometimes seen issues with these things in converted documents, and although this is reduced when using unoconv because the references are refreshed before export, the problem still exists.

**Comment by dagwieers** [comment]
This seems a perfect example for the plugin-system we would like to introduce.
See #84 for more information.
