### ISSUE TITLE
Shaheed

### ISSUE THREAD

**Issue by shaheedcodon** [unoconv/unoconv#319]
Hi Sir,
 First of all thank you for developing beautiful source unoconv.
I have a small issue, i can be able convert all the supported documents . 
I have one excell sheet called Messages.xlsx". 
 when i try to convert it the whole program will be struck.. with out any error messages.
So i am simply killing all soffice.bin then unoconv again works cool...(Except for this document).
Fortunately remaining xlsx will work.
I have ubuntu 12.04lts
unoconv 0.4
libre office 4.2 (also same issue with Libre office 3.0).
Even i tried to upload that document  here then, this (github)  one is saying unsupported format.
I can open with libreoffice and do operations.
If required i will mail that document to your mail.
Please do reply.
Thanks in advance.

**Comment by regebro** [comment]
Is this still an issue?

**Comment by shaheedcodon** [comment]
Thank you for your response. I am not dealing with unoconv any more.
