### ISSUE TITLE
Conversion fails saying soffice.bin exited with 0

### ISSUE THREAD

**Issue by makailol** [unoconv/unoconv#321]
Hi

We are facing a issue where Unoconv spreadsheet to CSV conversion is not able to convert the files and fails silently. This happens randomly and trying again on same file always works. We are converting files through web request as web server user and for most cases we don't face any issue.

Command used for file conversion is
`unoconv -T 10 -vvvvv -f csv -o destFile srcFile`

When it fails to convert file, it outputs info like below. Here it seems that listener gets terminated before unconv can connect to it.

```
Office base location: /usr/lib64/libreoffice
Office binary location: /usr/lib64/libreoffice/program
Existing listener not found.
Launching our own listener using /usr/lib64/libreoffice/program/soffice.bin.
LibreOffice listener successfully started. (pid=18834)
Process /usr/lib64/libreoffice/program/soffice.bin (pid=18834) exited with 0.
```

Or sometimes it shows like below.

```
Office base location: /usr/lib64/libreoffice
Office binary location: /usr/lib64/libreoffice/program
Existing listener not found.
Launching our own listener using /usr/lib64/libreoffice/program/soffice.bin.
LibreOffice listener successfully started. (pid=20495)
```

We also tried to increase timeout value (--timeout=10) as suggested on man page but that did not helped. 

Installed packages
Os CentOS-6.4
unoconv 0.5
LibreOffice 4.2.8.2
Libreoffice-headless 4.2.8.2
Python 2.6.6

**Comment by regebro** [comment]
Is this still an issue?
