### ISSUE TITLE
Weird problem with decimal separator

### ISSUE THREAD

**Issue by sebelk** [unoconv/unoconv#324]
Hi,

I have a script with the following command:

```
unoconv -i FilterOptions=44,34,76 -f xls  ${ARCHIVOINFO}.csv
```

That script runs on CentOS 6.7

When I connect to Linux from Windows  (via SSH client) it outputs de xls correctly.

But when I run from a Linux ssh client the outputs is messed up.

For example, fields with values such a 0.80 are prepended with a single quote, so the value results as '0.80

And so, this field is rendered as text in the spreadsheet.

I've made a work around, the script ask user from which OS is conneting. But I wonder if there is a more clever way of do it.

Thanks in advance!

**Comment by paulggapps** [comment]
How did you resolve this as I'm having a similar problem?

The Word Document converts to PDF (tables and all) - one issue is the decimal separator is represented as 1/4

Any ideas?

**Comment by regebro** [comment]
Is this still an issue? Can you provide an example file?
