### ISSUE TITLE
Looking for a release-manager and contributors

### ISSUE THREAD

**Issue by dagwieers** [unoconv/unoconv#331]
As you have noticed, I don't have a lot of time to commit to unoconv. Someone proposed to help me with releasing Dstat versions, and this worked so well that I think this might be the solution for unoconv as well !

So I am looking for one or more persons who:
- can lend a hand in planning and releasing unoconv
- has a vested interest and is using unoconv on a regular basis (maybe professionally)
- can contribute to unoconv and understands python

I can offer you:
- commit access (i.e. commit and merge, bug-triage, release-management)
- the satisfaction of helping people and improving unoconv in Open Source
- a way to guide the decision process and direction unoconv is going

**Comment by regebro** [comment]
If I ping you here, will you see it? @dagwieers

**Comment by dagwieers** [comment]
@regebro I have seen a lot of activity :-) But swamped with work until end of March to spend any reasonable effort on anything. A few upcoming hard deadlines for Cisco and Ansible :-/

**Comment by dagwieers** [comment]
Anything specific that needs my attention right now ?

**Comment by regebro** [comment]
Yes, if you could move this repo to the unoconv organization that you created before, and give me access? Then I can merge a lot of things, and also give access to other people at the company I work for.

This is my last day at this job, but at my new job I use a macbook, so I'll continue to help with mac issues, even though I won't use Unoconv at work any more.

**Comment by dagwieers** [comment]
@regebro Oh sure, did not realize this was not already done (although the URL gives it away :-).

Hold on.

**Comment by dagwieers** [comment]
@regebro You're good to go ! I also pinned this issue to add some awareness.

**Comment by regebro** [comment]
Awesome1

**Comment by dagwieers** [comment]
I was hoping the new Python API would help, but to be honest I haven't looked at that the past 2 years.

**Comment by regebro** [comment]
Ah, so doing things by running macros, you mean? Yeah, maybe, why not.

**Comment by regebro** [comment]
Just to point out that while I am a release manager now, more active contributors are definitely appreciated, and that ranges from Libreoffice experts to people that want to help answer questions and maintain the issues, or review pull requests etc.

Open source is hard work, and the more people that contribute the better!

**Comment by regebro** [comment]
I'll close this issue, and start a new one similar!
