### ISSUE TITLE
Cannot run unoconv --listener

### ISSUE THREAD

**Issue by quanvn1206** [unoconv/unoconv#332]
i installed libreoffice5.0 and unoconv0.7 on ec2 amazon linux ami
then i cannot run unoconv --listener with error 

Launch of /opt/libreoffice5.0/program/soffice.bin failed.
loading component library file:///opt/libreoffice5.0/program/../program/libmergedlo.so failed

thanks for support

**Comment by NickFranceschina** [comment]
is unoconv being run with python3?   libreoffice5 ships with pyuno that only works in python3

**Comment by mackensen** [comment]
You could be missing a dependency. Try running `ldd /opt/libreoffice5.0/program/libmergedlo.so` and see if any of the modules report as "not found". On aws I found that I needed `dbus-glib` installed.

**Comment by nadavkav** [comment]
Try these packages: http://www.tecmint.com/install-libreoffice-on-rhel-centos-fedora-debian-ubuntu-linux-mint/ (It worked for me)

**Comment by mgancarzdsi** [comment]
Based on the output of ldd for libmergedlo.so, on CentOS 7 minimal, I was missing libGL and libcairo. Doing a yum install cairo fixed both for me.

**Comment by caadar** [comment]
The same on Gentoo (nomultilib profile), unoconv 0.7 and 0.8.2, libreoffice 5.4.4.2 or libreoffice-bin 5.4.2.2-r1, python 3.4, 3.5 and 3.6 tried:

`````
unoconv --listener &

Launch of /usr/lib/libreoffice/program/soffice.bin failed.
loading component library <file:///usr/lib64/libreoffice/program/../program/libmergedlo.so> failed
`````

```` ldd /usr/lib64/libreoffice/program/../program/libmergedlo.so ```` seems ok though.

**Comment by regebro** [comment]
If anyone still has this issue, ping me and I'll try to help narrow this issue down.

**Comment by jamesamurr-bind** [comment]
I seem to have a similar issue. On amazon linux 2. Running unoconv I get the following output:
```
Traceback (most recent call last):
  File "unoconv", line 842, in connect
    unocontext = resolver.resolve("uno:%s" % op.connection)
uno.NoConnectException: Connector : couldn't connect to socket (Connection refused)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "unoconv", line 1429, in <module>
    main()
  File "unoconv", line 1343, in main
    convertor = Convertor()
  File "unoconv", line 821, in __init__
    unocontext = self.connect(resolver)
  File "unoconv", line 853, in connect
    product = self.svcmgr.createInstance("com.sun.star.configuration.ConfigurationProvider").createInstanceWithArguments("com.sun.star.configuration.ConfigurationAccess", UnoProps(nodepath="/org.openoffice.Setup/Product"))
__main__.CannotActivateFactoryException: loading component library <file:///opt/libreoffice6.2/program/../program/libmergedlo.so> failed
```

`ldd /opt/libreoffice6.2/program/../program/libmergedlo.so |grep not` shows
`libSM.so.6 => not found`
`libICE.so.6 => not found`

The way that I installed LibreOffice was by downloading the rpm from here:
`http://download.documentfoundation.org/libreoffice/stable/6.2.4/rpm/x86_64/`

unzipping and doing
`sudo yum -y install RPMS/*.rpm`
which showed no errors

**Comment by redesitos** [comment]
Execute command yum install cups-libs and worked

**Comment by shaileshcheke** [comment]
@mackensen  thanks. You saved my time.
