### ISSUE TITLE
Making selections before conversion

### ISSUE THREAD

**Issue by dagwieers** [unoconv/unoconv#34]
In some cases users would like to make selections before doing the conversion, this could be useful in order to:
- select a specific sheet in a spreadsheet to convert (currently only the first sheet is converted)
- select a specific range in a spreadsheet to convert
- select a specific range of pages to convert

The difficulty here is two-fold:
- how do we describe the various pieces for doing the selection
- how do we instruct LibreOffice to perform the description of what the user needs

So a lot of discussion around this is needed to understand the various requirements and implementation bits. Feedback welcome

**Comment by lagah** [comment]
I make zonaj's changes, result:

# unoconv3 -d spreadsheet -f html --sheet='Físico' 2.xlsx
  File "/usr/bin/unoconv3", line 856
    sheets.moveByName (op.sheetname, 0)
                                                                   ^
IndentationError: unindent does not match any outer indentation level

**Comment by emoreth** [comment]
+1 for choosing sheets to export

Is this intended to be merged/re-implemented anytime ?
