### ISSUE TITLE
setup problem can't read /var/mail/__future__

### ISSUE THREAD

**Issue by sebastianmng** [unoconv/unoconv#344]
I'm working with unoconv 0.7 HEAD from homebrew and LibreOffice 5.1.3.2 from homebrew cask on a Mac OS X Yosemite. In addition, since I had the issue described in [#211](https://github.com/dagwieers/unoconv/issues/211)  I changed the shebang in unoconv to #!/Applications/LibreOffice.app/Contents/MacOS/python

Running `unoconv -f  pdf ~/Documents/somedirectory/somefile.doc` in terminal returns

> from: can't read /var/mail/**future**
> from: can't read /var/mail/distutils.version

followed by several options for image settings. I get the same from running simply `unoconv` so I believe this is a setup problem as stated in  [#320](https://github.com/dagwieers/unoconv/issues/320) but I'm unable to find a solution after following the steps for troubleshooting.

**Comment by regebro** [comment]
How unoconv installs itself is slightly different now, is this still an issue if you `pip install unoconv`?

**Comment by DaveMellor** [comment]
> How unoconv installs itself is slightly different now, is this still an issue if you `pip install unoconv`?

Sorry, but I am still getting this problem on Ubuntu 20.04 LTS (you must be sick to death of this but if you can help I'd be obliged. :)
