### ISSUE TITLE
Make `unoconv` more (re)usable from within other Python modules

### ISSUE THREAD

**Issue by alexmorozov** [unoconv/unoconv#345]
Hello @dagwieers , thanks a lot for a fantastic tool!

I'm trying to couple it with some custom Django templating tool and noticed that `unoconv` is not very convenient when it comes to using it as a library. There's a bunch of global shared variables all key components rely upon. For comparison, there's `PyODConverter`, which (despite the fact it's quite outdated) plays really nicely being used within other modules.

So my question is: Does that tight coupling exist intentionally, or should we perhaps make things more decoupled and integration-friendly? Think of it as a public API.  As it will apparently break backwards compatibility (methods' signatures will change), I'd like to get your buy-in first, before doing any work on PR.

**Comment by dagwieers** [comment]
There was a PR with this intention, but there was a reason why I did not merge it (yet).

So I don't mind making unoconv better to integrate with, but remember since we are running libreoffice, it may not be as worthwhile to do. I am contemplating looking into using libreoffice as a (native python) library as well. And then things would become more stable, faster and more interesting.

**Comment by alexmorozov** [comment]
Dag, please correct me if I'm wrong, but since we can feed a `connection` option to `unoconv`, we can use a standalone headless server being fired up in advance, so that we don't have to wait starting libreoffice each time we want to convert a document. As a matter of fact, this is exactly our case: we start libreoffice via supervisor, and then have pyodconverter connect to it and do its dirty stuff. It has been working for 4 years doing about 100-200 conversions per day, but we're going to move to Python3, and PyODConverter seems to be just too dated to stick to.

Please elaborate a bit on using libreoffice as a native library, that's news to me. Is there another bridge API besides UNO?

**Comment by dagwieers** [comment]
Well, my experience is that LibreOffice from time to time (less than it used to) crash, become unstable or aggregates more memory). Another issue is that the headless instance only works with a single connection, although it happily accepts more, but becomes unstable when doing more than one conversion. So this way of working is error-prone (look at the may numbers of issues reported).

**Comment by alexmorozov** [comment]
I totally agree with you that LibreOffice is a far cry from a rock-solid software. To some extent this can be fixed by wrapping it with some kind of a, uhm, supervisor. But hey, we have what we have, and I, for instance, haven't heard of any other decent solution. So did I understand you correct that you don't mind a PR with a more loosely coupled components? Are there any things I should watch out for? Like those the author of a previous pull request haven't done ).

**Comment by dveselov** [comment]
@alexmorozov have you tried [pylokit](https://github.com/xrmx/pylokit)?

**Comment by alexmorozov** [comment]
@dveselov , thanks for a pointer, looks really promising! Will give it a spin.

**Comment by alexmorozov** [comment]
Unfortunately, `pylokit` doesn't seem to work with neither older LibreOffices which don't have LibreOfficeKit, nor the new one (5.1.4) - it just fails silently. So does `lloconv` itself, so I guess something has changed in LO internals since then. And btw, I just realized that it would have to load entire LO in memory, convert, and then unload it. So my concern is the overall speed.
Thus, I'd stick to `unoconv`, hope I'll have some spare time to try make it a bit more integration-friendly.

**Comment by dveselov** [comment]
Uh.
I'm using `pylokit` right now with `LibreOffice 5.1.4.2` running on Ubuntu 16.04 and all works perfectly.
Did you have correct enviropment? For ubuntu all needed packages can be installed by `apt-get install libreoffice libreofficekit-dev libffi-dev && pip install pylokit`

**Comment by alexmorozov** [comment]
Yes, I have all the packages and stuff, except I'm on 14.04. Well I can't help but tell the words of worship to `strace` one more time. It turned out that it was stale LibreOffice config files in my home directory which for unknown reason were owned by root. So LibreOfficeKit (being run by unprivileged user) wasn't being able to open those files and was crashing silently. Now everything works, thanks Dmitry!

@dagwieers really sorry for the offtopic, feel free to sweep us away from this thread.
