### ISSUE TITLE
unoconv: Cannot find a suitable pyuno library and python binary combination in /usr/lib/libreoffice ERROR: No module named uno

### ISSUE THREAD

**Issue by sTb1337** [unoconv/unoconv#354]
have the same error on Ubuntu 14.04.

sq006wqa01:/usr/bin# export UNOPATH=/usr/bin/libreoffice
sq006wqa01:/usr/bin# echo $UNOPATH
/usr/bin/libreoffice
sq006wqa01:/usr/bin# unoconv -vvv --show
unoconv: Cannot find a suitable pyuno library and python binary combination in /usr/lib/libreoffice
ERROR: No module named uno

unoconv: Cannot find a suitable office installation on your system.
ERROR: Please locate your office installation and send your feedback to:
http://github.com/dagwieers/unoconv/issues

Ive found https://github.com/dagwieers/unoconv/issues/49 but its closed and i dont know how to reopen it.

**Comment by regebro** [comment]
You also need to run unoconv with the Python installation from the Libreoffice.
There's more information on #49 now.
