### ISSUE TITLE
Magnification=2 

### ISSUE THREAD

**Issue by korvinko** [unoconv/unoconv#355]
unoconv -f pdf -e Magnification=2 /tmp/test.xlsx
This does not have any affect on result pdf.

unoconv --version
unoconv 0.7
Written by Dag Wieers dag@wieers.com
Homepage at http://dag.wieers.com/home-made/unoconv/
platform posix/linux
python 3.5.2 (default, Jun 28 2016, 08:46:01) 
[GCC 6.1.1 20160602]
LibreOffice 5.2.1.2

**Comment by regebro** [comment]
I could be that the PDF reader ignores it. I don't have a reader that not ignore it, so I can't test it.

**Comment by ConnorShride** [comment]
Any resolution or notes on this one? Ditto to the usage above, and experiencing the same issue with when paired with the Zoom option as well.

unoconv --format=pdf --output=/tmp/foo.pdf -P PaperOrientation=landscape -e Magnification=4 -e Zoom=150 ./foo.xls

Has no effect on the pdf.

unoconv --version
unoconv 0.9.0
Written by Dag Wieers <dag@wieers.com>
Homepage at http://dag.wieers.com/home-made/unoconv/

platform posix/linux
python 3.6.9 (default, Jul 17 2020, 12:50:27) 
[GCC 8.4.0]
LibreOffice 6.0.7.3
