### ISSUE TITLE
help to install unoconv on ubuntu 14.04 amazon ec2 instance

### ISSUE THREAD

**Issue by dnyaneshw** [unoconv/unoconv#362]
I have installed unoconv in on ubuntu server ec2 instance.
sudo apt-get install unoconv
but document conversion (word,.odt, .doc, .xlsx to pdf )didn't work is there any dependency which i need to install, to make it work.
or please provide me the step by step guide to install it on ubuntu server 14.04 amazon ec2 instance

**Comment by priyankinfinnov** [comment]
Did you find the answer to this?

**Comment by regebro** [comment]
`sudo apt-get install unoconv libreoffice` should work.
