### ISSUE TITLE
odt to pdf works but not correctly

### ISSUE THREAD

**Issue by andyideologi** [unoconv/unoconv#366]
I am using Unoconv 0.7. In unoconv first line is set as '#!/usr/bin/env python3'.
Libreoffice 4.3.6.2.

shell_exec('/usr/bin/unoconv -f pdf AnandLagad.odt');

this command convert odt to pdf but not perfectly. Means some data like headers are not shown in pdf which are present in odt file.

**Comment by regebro** [comment]
Nothing in life is perfect. :-)

The question is of Libreoffice can export the document to PDF correctly?
