### ISSUE TITLE
Is there any way to get the index of pdf file

### ISSUE THREAD

**Issue by kiranps** [unoconv/unoconv#367]

**Comment by regebro** [comment]
I don't know what this question means, or what it has to do with unoconv.

**Comment by dagwieers** [comment]
My CV converted from asciidoc to ODT includes a proper index in the PDF.
So LibreOffice supports this fine and exports it correctly to PDF.
(LibreOffice has a very complete PDF exporter, which is why I wrote unoconv in the first place)
