### ISSUE TITLE
HTML to Docx conversion is super-slow

### ISSUE THREAD

**Issue by trushkevich** [unoconv/unoconv#380]
Hi. I'm not sure what is going on, but on machine with Ubuntu 16.04 converting 13kB HTML to docx takes 1 to 5 (again it's not clear what causes different times) minutes having these versions installed:
```
$ unoconv --version
unoconv 0.7
Written by Dag Wieers <dag@wieers.com>
Homepage at http://dag.wieers.com/home-made/unoconv/

platform posix/linux
python 3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609]
LibreOffice 5.1.4.2
```
This machine has 32 GB RAM of which 28 are free during conversion and also has Intel(R) Xeon(R) CPU E5-2640 v4 @ 2.40GHz which is idle for like 99.7% during conversion.

While on Ubuntu 14.04 machine with 8GB RAM and Core i7 4700 with:
```
$ unoconv --version
unoconv 0.6
Written by Dag Wieers <dag@wieers.com>
Homepage at http://dag.wieers.com/home-made/unoconv/

platform posix/linux
python 3.4.3 (default, Nov 17 2016, 01:08:31) 
[GCC 4.8.4]
LibreOffice 4.2
```
it takes a couple of seconds.

Any idea about what can be the issue and how I can troubleshoot this ? Thanks.

**Comment by regebro** [comment]
How long does it take if you use soffice.bin directly to convert it?
