### ISSUE TITLE
Cannot convert any document type

### ISSUE THREAD

**Issue by jonycp** [unoconv/unoconv#386]
Hello,

We have

Ubuntu 16.04.2 LTS

/usr/bin/unoconv --version
unoconv 0.7
...
platform posix/linux
python 3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609]
LibreOffice 5.1.6.2

We are using Moodle and trying to convert for comments in grading.  At this time, command line shows:
sudo /usr/bin/unoconv -vvv -f pdf TestWord2013Document.docx
Verbosity set to level 3
Using office base path: /usr/lib/libreoffice
Using office binary path: /usr/lib/libreoffice/program
DEBUG: Connection type: socket,host=127.0.0.1,port=2002,tcpNoDelay=1;urp;StarOffice.ComponentContext
DEBUG: Existing listener not found.
DEBUG: Launching our own listener using /usr/lib/libreoffice/program/soffice.bin.
LibreOffice listener successfully started. (pid=20690)
Input file: TestWord2013Document.docx
unoconv: RuntimeException during import phase:
Office probably died. Unsupported URL <TestWord2013Document.docx>: "type detection failed"
DEBUG: Terminating LibreOffice instance.
DEBUG: Waiting for LibreOffice instance to exit.

I made sure to chown apache user /var/www but no help.  I can't find any more information on this, so seeking advice.

Thanks,

Jon

**Comment by aislandener** [comment]
Hi,

Check your installation of libreoffice to see if it is complete, as I encountered this same error, and after reinstalling it with all the packages that were resolved.

**Comment by regebro** [comment]
You also get "type detection failed" when the file is broken, but it says it can't convert any type, so that shouldn't be it.
