### ISSUE TITLE
unoconv on Windows XP + cygwin : Cannot find a suitable office installation on your system

### ISSUE THREAD

**Issue by bourne-again** [unoconv/unoconv#395]
Hi,

I installed the latest LibreOffice 5.3.3 today on a freshly installed legacy-forever system running Windows XP (32 bit). I then installed cygwin (from a dump that I maintain) and did git clone for unoconv. Trying to run unoconv gets me "Cannot find a suitable office installation on your system".

This issue has been reported earlier, but the page did not provide a resolution. So I am reporting it again, with details of my setup : 

1) LibreOffice binaries at C:\Program Files\LibreOffice 5\program
2) I have manually added an env var UNO_PATH set to "C:\Program Files\LibreOffice 5\program"

I have also tried running unoconv by first copying it into the LibreOffice 5\program folder. This does not help.

Any help from you would be appreciated. Thanks.
Manish Jain

**Comment by erlinux** [comment]
Seek help...

**Comment by regebro** [comment]
There should be a Python exe included with Libreoffice, and you should run unoconv with that. I haven't tried this on Windows, though, so I can't tell you exactly.

Issue #49 has more information, but that's mostly for Linux, so it may not be helpful.
