### ISSUE TITLE
Create encrypted/password protected document

### ISSUE THREAD

**Issue by HeuvelTop** [unoconv/unoconv#397]
For secure exchange of data from web site it would be helpful to be able to encrypt/password protect downloaded documents.

Currently version 0.7 --password is only working to decrypt a source document.

What I look for is from csv to encrypted ods/xls.

**Comment by HeuvelTop** [comment]
Has this enhancement ever been created/implemented? It would still be a very welcome security enhancement for my web site serving an international network of activists.

**Comment by wonjoonSeol-WS** [comment]
Note that while regebro closed this as completed, encryption is still not supported.
unoconv --password=1234 -f xlsx test123.csv 

This does not work. There is no PR in unoserver mentioning encryption either so I doubt it works in the new repo neither.
