### ISSUE TITLE
ERROR: No module named unohelper

### ISSUE THREAD

**Issue by cybersthang** [unoconv/unoconv#408]
unoconv: Cannot find a suitable pyuno library and python binary combination in /usr/lib/libreoffice
ERROR: No module named unohelper

unoconv: Cannot find a suitable office installation on your system.
ERROR: Please locate your office installation and send your feedback to:
       http://github.com/dagwieers/unoconv/issues
I using Ubuntu 14.04 and python 2.7. but i don't install unoconv. how to fix ?

**Comment by regebro** [comment]
Strange. Is this still a problem?

**Comment by MrPeak** [comment]
Yes, still

**Comment by regebro** [comment]
I've noticed that when these issues arise, the solution is to run unoconv with the python executable that comes with the Libreoffice installation you want to use. Like so:

```
UNOPATH=/path/to/Libreoffice /path/to/Libreoffice/program/python /usr/bin/unoconv ....
```
Yes, that's fairly annoying, but only happens with multiple LibreOffice and/or Python installations.
See issue #49 for more information.

**Comment by programmer8396** [comment]
Ubuntu 14.04, python 2.7 , 


![Screenshot from 2021-02-04 19:12:20](https://user-images.githubusercontent.com/57538011/106901247-6acd7a00-66ef-11eb-828f-6fa8f0194401.png)

I want to use  aeroo_report in Openerp6.1 
I tried 
**sudo apt-get install libreoffice python-genshi python-cairo python-lxml python-setuptools

sudo apt-get install libreoffice-script-provider-python

then try to installed the uno package**

but doesn't work for me
