### ISSUE TITLE
No Version 0.7 for Freebsd

### ISSUE THREAD

**Issue by turbocyx** [unoconv/unoconv#410]
When will t here be a 0.7 for Freebsd. Need it, because moodle depends on it ....

**Comment by regebro** [comment]
Could you install from the 0.7 zip file?

**Comment by turbocyx** [comment]
Which one?

 

Von: Lennart Regebro [mailto:notifications@github.com] 
Gesendet: Donnerstag, 12. Oktober 2017 20:47
An: dagwieers/unoconv <unoconv@noreply.github.com>
Cc: turbocyx <turbocyx@gmail.com>; Author <author@noreply.github.com>
Betreff: Re: [dagwieers/unoconv] No Version 0.7 for Freebsd (#410)

 

Could you install from the 0.7 zip file?

**Comment by regebro** [comment]
https://github.com/dagwieers/unoconv/archive/0.7.zip

**Comment by turbocyx** [comment]
Ahh, yes. Tried that, but won’t work in freebsd:

make: Unknown modifier ' '

make: "/root/unoconv-0.7/Makefile" line 37: Missing dependency operator

make: "/root/unoconv-0.7/Makefile" line 41: Need an operator

make: "/root/unoconv-0.7/Makefile" line 80: Missing dependency operator

make: "/root/unoconv-0.7/Makefile" line 96: Need an operator

make: "/root/unoconv-0.7/Makefile" line 98: warning: duplicate script for target "rewrite" ignored

make: "/root/unoconv-0.7/Makefile" line 88: warning: using previous script for "rewrite" defined here

make: "/root/unoconv-0.7/Makefile" line 101: warning: duplicate script for target "restore" ignored

make: "/root/unoconv-0.7/Makefile" line 95: warning: using previous script for "restore" defined here

make: "/root/unoconv-0.7/Makefile" line 102: Need an operator

 

Gues there need to be  some modifications in Makefile, but I dont know exactly what ….

**Comment by turbocyx** [comment]
Will try installation by hand …

**Comment by regebro** [comment]
Yeah, it's just a python script so you don't need to compile anything, you can just copy the script.
Will need to look into why it doesn't work on freebsd, then.

**Comment by regebro** [comment]
Since 0.8 you should now be able to install it with `pip install unoconv`
