### ISSUE TITLE
Converting docx to html, not converting tables

### ISSUE THREAD

**Issue by joeconradt** [unoconv/unoconv#435]
I'm converting Word documents that contain a simple table. However, the table is not converting over, nor any content inside of it. Is this a limitation with unoconv?

**Comment by regebro** [comment]
No, that works for me. Do you have an example document?

**Comment by maganvill** [comment]
@regebro, please look at #330

**Comment by regebro** [comment]
Do you have an example document?

**Comment by maganvill** [comment]
The document in #330. Table is not rendered.

**Comment by maganvill** [comment]
Any clue @regebro?

Thank you so much in advance.
