### ISSUE TITLE
Input file is .docx; output file is .docx; applying template; "-preserve" not working 

### ISSUE THREAD

**Issue by DavidAyliffe** [unoconv/unoconv#438]
Hi

I am using unoconv to add a template to a docx file and output a new docx file.  This is working fine, but I'm using the -preserve switch which I expect to preserve the "created by" and "created date" info.  This is not working.

Is this issue by design or is it a bug?

my Perl call looks similar to this:
system ( 'unoconv', '-t', $template, '--preserve', '-o', $newDOCX, '-f', "docx", $originalDOCX )

Thanks

**Comment by regebro** [comment]
I can't reproduce this. What os and filesystem is it? Does the user have permissions to change file metadata?
