### ISSUE TITLE
Filename length longer than 30 characters: error in .xlsx file  (.csv import)

### ISSUE THREAD

**Issue by hasorli** [unoconv/unoconv#439]
Sheet name length in MS Excel is max 30 characters. The file name will be added to the Sheet name. If the filename is longer than 30 characters it will make a error in the file.

If you open a .xlsx file with a sheet name longer than 30 characters you get this error. 

![skjermbilde 2018-02-17 kl 10 01 53](https://user-images.githubusercontent.com/174438/36339620-13d23c98-13ca-11e8-8593-254a05dde84b.png)

The log file from the file fix: 

> <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
> <recoveryLog xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><logFileName>Repair Result to abcdefghijklmnopqrstuvwxyz123_31 04063.xml</logFileName><summary>Errors were detected in file 'Macintosh HD:Users:xyz:Desktop:abcdefghijklmnopqrstuvwxyz123_31.xlsx'</summary><repairedRecords summary="Following is a list of repairs:"><repairedRecord>Repaired Records: Worksheet properties from /xl/workbook.xml (Workbook)</repairedRecord></repairedRecords></recoveryLog>
> 

```
$ unoconv --version
unoconv 0.7
platform posix/linux
python 3.3.5 (default, Feb  5 2016, 10:53:34) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)]
LibreOffice 5.0.5.2
```

unoconv-prove-error.sh makes test files that shows the case. 

```
#!/bin/bash
# unoconv-prove-error.sh,  2017 havard@sorli.no
# Unoconv - Libre Office, debug https://github.com/dagwieers/unoconv/issues/439

lfile=abcdefghijklmnopqrstuvwxyz123_
sfile=abcdefghijklmnopqrstuvwxyz12_

ext=".csv"
format="xlsx"

x=$0
y=${x%.*}
sname=${y##*/}
stmpdir=$(mktemp -t -d ${sname}.XXXX) || { echo "Failed to create temp dir"; exit 1; }

lfilechar=$(echo $lfile | wc -m)
sfilechar=$(echo $sfile | wc -m)

lfile=$lfile$lfilechar
sfile=$sfile$sfilechar

echo "                                                    "
echo "Sample directory:     :  "  $stmpdir
echo "                                                    "
echo "Filename prefix                 Number of characters"  
echo "----------------------------------------------------"
echo $lfile "  "  $lfilechar
echo $sfile "   " $sfilechar
echo "                                                    "

# File, from here doc, long filename
cat << EOF > $stmpdir/$lfile$ext
col1
EOF

# File, shorter filename
cp $stmpdir/$lfile$ext $stmpdir/$sfile$ext

echo "Convert from csv to "$format
unoconv --doctype spreadsheet --import FilterOptions=1,,1,1 --format $format $stmpdir/$lfile$ext
unoconv --doctype spreadsheet --import FilterOptions=1,,1,1 --format $format $stmpdir/$sfile$ext

find $stmpdir/*.$format -exec ls {} \; 
echo "                                                    "

echo "Open file with $lfilechar characters, $lfile.$format in Excel, to get the error message". 
echo "Open file with $sfilechar characters, $sfile.$format in Excel. Works. No error."
echo "                   

```

Suggested solutions
---
The problem can be reproduced by open .csv file (with 31 characters in the filenane) and save to .xlsx in LibreOffice.   LibreOffice 5.1.62 (on Mac OS X) and LibreOffice  Version: 6.0.1.1 (Mac OS X)

1. Document the issue
2. Show a warning on the issue. 
3. Shorten the filename (Sheet name) with a number at the end (aka Sheet01, Sheet02) and show a warning on the issue.

**Comment by regebro** [comment]
So testing with LibreOffice shows that it will indeed happily create Excel files with sheet names longer than 30 characters. So this is actually a LibreOffice issue, not a unoconv issue. Of course, it would be possible to work around it in unoconv, but I'm not sure it's the right thing to do.
