### ISSUE TITLE
LibreOffice 6 doesn't have internal python binary?

### ISSUE THREAD

**Issue by MartinPaulEve** [unoconv/unoconv#454]
Hi,
I'm getting the familiar "unoconv: Cannot find a suitable pyuno library and python binary combination in /usr/lib/libreoffice" and have tracked it down to there being no python or python.bin file anywhere within my LibreOffice 6 installation. Is this a change to the way that python is handled in LO6 that would break unoconv?
Martin

**Comment by AlmogBaku** [comment]
any update?

**Comment by regebro** [comment]
No, many system distributions of Libreoffice will not have an included python, but use the system python, so that would be /usr/bin/python3 in this case.

**Comment by MartinPaulEve** [comment]
Yeah, but @regebro, that simply doesn't work, say on the default install of Ubuntu. Changing the #! to /usr/bin/python3 just results in the ERROR: No module named 'base' error.

**Comment by regebro** [comment]
Hm. That's strange.

**Comment by MartinPaulEve** [comment]
Yeah - I've had no success on any Ubuntu 18.04 machine, regardless of which python binary I use.

**Comment by regebro** [comment]
Is python3-uno installed? It's a requirement of Libreoffice, but it seems like it's not a hard requirement, so possibly it's possible to have Libreoffice installed without it?

Also, theoretically, there could be another version of the uno package installed in the Python search path that messes things up.

Try this: `python3 -c "import uno; print(uno.__file__)"`

It should output `/usr/lib/python3/dist-packages/uno.py`

**Comment by MartinPaulEve** [comment]
Thanks for the reply.

OK, so python3-uno is installed via apt:

`sudo apt install python3-uno
[sudo] password for martin: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-uno is already the newest version (1:6.0.7-0ubuntu0.18.04.2).`

However, running the import yields:

`python3 -c "import uno; print(uno.__file__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/uno/__init__.py", line 4, in <module>
    from base import Element, Css, Payload, UnoBaseFeature, UnoBaseField
ModuleNotFoundError: No module named 'base'`

**Comment by regebro** [comment]
Aha! I also had that problem. It's because I at some time ran "pip install uno". That, unfortunately, downloads and install [an HTML converter also called uno](https://pypi.org/project/uno/). 

`pip uninstall uno` should deal with that.

**Comment by MartinPaulEve** [comment]
OK, so I did a pip uninstall uno, both system-wide and inside the virtualenv. This _was_ installed. I then did an apt --reinstall of python3-uno.

In system:

```
python3 -c "import uno; print(uno.__file__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/uno/__init__.py", line 4, in <module>
    from base import Element, Css, Payload, UnoBaseFeature, UnoBaseField
ModuleNotFoundError: No module named 'base'
```

In virtualenv:

```
python3 -c "import uno; print(uno.__file__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'uno'

```
Thanks for the advice debugging this. Would be great to track it down and write up the pitfalls to avoid.

**Comment by regebro** [comment]
Yeah, I'll leave this open with a Documentation tag.

**Comment by MartinPaulEve** [comment]
Thanks for all your work here. Do let me know if there are other things I should test as I'd love to get this working but am still in breakage :(

**Comment by regebro** [comment]
No, you seem to still have the uno module locally, so try deleting the whole `/usr/local/lib/python3.6/dist-packages/uno/`.

To make a virtualenv with uno you need to point it to the correct Python exe and have the `--system-site-packages` flag. This worked for me:

`virtualenv -p /usr/bin/python3 --system-site-packages withuno`

**Comment by MartinPaulEve** [comment]
Oh brilliant! I got it. I had to uninstall using pip3 as the standard pip install was a 2.7 install.

Thank you so much for taking the time here!

**Comment by aun408** [comment]
I'm having issue running one pipenv, any way that I can using pipenv like 

`virtualenv` -p /usr/bin/python3 --system-site-packages withuno`

**Comment by regebro** [comment]
No, unoconv must be run with the same python that Libreoffice uses.
