### ISSUE TITLE
Unconvert:  Exception encountered.

### ISSUE THREAD

**Issue by mrpatel0** [unoconv/unoconv#467]
I get an error when I execute unoconv with libreoffice:
UNO_PATH=/opt/libreoffice5.3 /usr/bin/unoconv -f xhtml schedule.docx
wait

Someone, please help.
Thanks!

===========ERROR================================

Traceback (most recent call last):
  File "/usr/bin/unoconv", line 1129, in convert
    document.storeToURL(outputurl, tuple(outputprops) )
uno.IOException: SfxBaseModel::impl_store 

<file:///var/www/sch/sdoc/s.html> failed: 0x20d

During handling of the above exception, another exception 

occurred:

Traceback (most recent call last):
  File "/usr/bin/unoconv", line 1400, in <module>
    main()
  File "/usr/bin/unoconv", line 1316, in main
    convertor.convert(inputfn)
  File "/usr/bin/unoconv", line 1131, in convert
    raise UnoException("Unable to store document to %s 

(ErrCode %d)\n\nProperties: %s" % (outputurl, e.ErrCode, 

outputprops), None)
  File "/opt/libreoffice5.3/program/uno.py", line 504, in 

_uno_struct__getattr__
    return getattr(self.__dict__["value"], name)
AttributeError: ErrCode

**Comment by regebro** [comment]
The error seems to indicate that it can't write to the file, try another location with -o /path/to/outputfile.html
