### ISSUE TITLE
Unoconv cannot start a new instance when libreoffice is already launched

### ISSUE THREAD

**Issue by DamienRobert** [unoconv/unoconv#470]
With unoconv 0.8.2 and libreoffice 6.1.1, here are the output I get in -vvv mode:

1) Unoconv without libreoffice started:
~~~
Verbosity set to level 3
Using office base path: /usr/lib/libreoffice
Using office binary path: /usr/lib/libreoffice/program
DEBUG: Connection type: socket,host=127.0.0.1,port=2002,tcpNoDelay=1;urp;StarOffice.ComponentContext
DEBUG: Existing listener not found.
DEBUG: Launching our own listener using /usr/lib/libreoffice/program/soffice.bin.
LibreOffice listener successfully started. (pid=15829)
Input file: rens-rh.odt
Selected output format: Portable Document Format [.pdf]
Selected office filter: writer_pdf_Export
Used doctype: document
Output file: file:///tmp/rens-rh.pdf
DEBUG: Terminating LibreOffice instance.
DEBUG: Waiting for LibreOffice instance to exit.
~~~

2) Unoconv with libreoffice started:
~~~
Verbosity set to level 3
Using office base path: /usr/lib/libreoffice
Using office binary path: /usr/lib/libreoffice/program
DEBUG: Connection type: socket,host=127.0.0.1,port=2002,tcpNoDelay=1;urp;StarOffice.ComponentContext
DEBUG: Existing listener not found.
DEBUG: Launching our own listener using /usr/lib/libreoffice/program/soffice.bin.
LibreOffice listener successfully started. (pid=15920)
DEBUG: Process /usr/lib/libreoffice/program/soffice.bin (pid=15920) exited with 0.
Error: Unable to connect or start own listener. Aborting.
~~~

3) unoconv --listener
~~~
Verbosity set to level 3
Using office base path: /usr/lib/libreoffice
Using office binary path: /usr/lib/libreoffice/program
Start listener on 127.0.0.1:2002
Existing LibreOffice listener found, nothing to do.
~~~

4) unoconv after calling `unoconv --listener`
~~~
Verbosity set to level 3
Using office base path: /usr/lib/libreoffice
Using office binary path: /usr/lib/libreoffice/program
DEBUG: Connection type: socket,host=127.0.0.1,port=2002,tcpNoDelay=1;urp;StarOffice.ComponentContext
Input file: rens-rh.odt
Selected output format: Portable Document Format [.pdf]
Selected office filter: writer_pdf_Export
Used doctype: document
Output file: file:///tmp/rens-rh.pdf
~~~

So starting `unoconv --listener`, even through it detects a running libreoffice instance, is enough for subsequent calls of unoconv to succeed. Looking at the source code, the difference is that `Listener` 
redefine `product = self.svcmgr.createInstance(...)`
after the call to `unocontext = resolver.resolve("uno:%s" % op.connection)`
(so I don't know if the first definition of `product` is used actually...)
while `connect`, in "Launching our own listener using" does not redefine `product` after this `resolve` call.

Wouldn't it be better in `connect` to call `Listener` directly rather than duplicate the code?

**Comment by regebro** [comment]
Well, but it's probably not listening on the correct port. I don't know if this can be worked around, but I agree it's annoying when it happens.

**Comment by k8scat** [comment]
I also meet this problem `Existing LibreOffice listener found, nothing to do`, is there any solution?

Else, I can start unoconv program while I killed `/opt/libreoffice5.4/program/soffice.bin` process.

**Comment by centic9** [comment]
I encounter the same reproducible when first opening LibreOffice manually and then running unoconv. The first call fails, the 2nd one works.

I use a workaround of simply re-trying the connection in this case, see https://github.com/centic9/unoconv-ppa/blob/ppa/0.7-2/debian/patches/0004-prevent-failure-with-running-libreoffice.patch#L43 for the patch.
