### ISSUE TITLE
Problem with charset. run command unoconv  from php server

### ISSUE THREAD

**Issue by Deneiz** [unoconv/unoconv#472]
Hi! when i run command **`sudo unoconv -i utf8 -f txt /home/denis/web/sites/hr.dev/public/tmp/resume_2.docx`** from linux console - all right.

But when i try to run same command from php server i have a problem with charset.

![default](https://user-images.githubusercontent.com/43852693/46479121-09333300-c7f7-11e8-8189-0ef6813eceaf.png)

Please, help!

**Comment by regebro** [comment]
I can't replicate this.
