### ISSUE TITLE
LibreOffice 6.1.2.1 install not found on windows10 (solution included)

### ISSUE THREAD

**Issue by pakal** [unoconv/unoconv#473]
I added this near line 92 of unoconv.py so that the x64 "C:\Program Files" folder gets searched when seeking LibreOffice install:

```
            if 'PROGRAMW6432' in list(os.environ.keys()):
                extrapaths += glob.glob(os.environ['PROGRAMW6432']+'\\LibreOffice*') + \
                              glob.glob(os.environ['PROGRAMW6432']+'\\LibreOffice\\program') + \
                              glob.glob(os.environ['PROGRAMW6432']+'\\OpenOffice.org*')
```

**Comment by lun471k** [comment]
Correct me if I'm wrong, but I think there's an additionnal backslack missing for `\program` on your third line.

Thank you very much for this fix, you saved me.

**Comment by pakal** [comment]
Indeed, I updated my solution, thanks
