### ISSUE TITLE
unoconv: UnoException during import phase: could not be opened.

### ISSUE THREAD

**Issue by NoumanDilshad** [unoconv/unoconv#483]
I am having this issue while converting all the files other then docx. docx file is converting fine. But other then that, All other office files (xls,xlxs,ppt,pptx) have this issue.
```
unoconv: UnoException during import phase:
The document 'file:///app/uploads/xlsfile.xls' could not be opened.
```

**Comment by regebro** [comment]
It works for me, could you post your command line and maybe an example file?
