### ISSUE TITLE
Updating index phase can result in poorer document conversion

### ISSUE THREAD

**Issue by chrisgillis** [unoconv/unoconv#484]
Thank you for this excellent project!

There is an issue with LibreOffice 6.1 (and probably older versions too) where if you right click a Table of Contents from MS Word .docx and select Update Indexes, it will arbitrarily remove 90% of the TOC data. Updating index equivalent in MS Word does not cause this behavior.

https://github.com/dagwieers/unoconv/blob/master/unoconv#L1044

This phase updates the indexes of TOC's which often results in a document far worse off than if the page numbers were off by one. (Better to have inaccurate page numbers than a missing TOC)

Here are some screenshots. I realize this is mostly a LibreOffice issue, but figured I'd also report it here in case there is another possible solution.

It is worth mentioning that running `soffice --headless --convert-to pdf` results in a perfectly fine PDF with the TOC correctly in place, without any missing data, presumably because their pdf conversion does not update indexes.

![image](https://user-images.githubusercontent.com/40451/50691453-c0aa3200-0ffe-11e9-9932-45118961c42b.png)

![image](https://user-images.githubusercontent.com/40451/50691469-c7d14000-0ffe-11e9-89b8-852bbb6459c9.png)

![image](https://user-images.githubusercontent.com/40451/50691472-cbfd5d80-0ffe-11e9-8fca-e422b08c0b17.png)

**Comment by regebro** [comment]
A flag to disable the index updating would make sense.
