### ISSUE TITLE
unoconv: Cannot find a suitable pyuno library and python binary combination

### ISSUE THREAD

**Issue by Lakshmipathi** [unoconv/unoconv#49]
I did a git clone and running into following error message.  I don't have openoffice but I have libreoffice write/calc/Impress installed on my machine. Any thoughts what's the issue? (I'm using Fedora16 and Python-2.7.2) 
# ./unoconv

unoconv: Cannot find a suitable pyuno library and python binary combination in /usr/lib64/libreoffice
ERROR: Please locate this library and send your feedback to:
       http://github.com/dagwieers/unoconv/issues
No module named uno
unoconv: Cannot find a suitable office installation on your system.
ERROR: Please locate your office installation and send your feedback to:
       http://github.com/dagwieers/unoconv/issues

**Comment by Easthy** [comment]
```$unoconv --listener &                                                                                                                                                
[1] 26217                                                                                                                                                                                                                                                                      
$:/var/www/v2/socAgency/branches/testNewBase/app/Console$ unoconv: Cannot find a suitable pyuno library and python binary combination in /usr/lib/libreoffice                                                                 
ERROR: No module named uno

unoconv: Cannot find a suitable office installation on your system.
ERROR: Please locate your office installation and send your feedback to:
       http://github.com/dagwieers/unoconv/issues
```
Kubuntu 14.04 64bit

```
 sudo  apt-get install openjdk-6-jdk libreoffice-core libreoffice-common libreoffice-writer python-uno
Package python-uno is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or is only available from another source
These packages could replace them
  libreoffice-script-provider-python
```

**Comment by yellowiscool** [comment]
@Easthy I had the same error on Ubuntu 14.04 and I fixed the problem by using python3 instead of python.

**Comment by sTb1337** [comment]
I have the same error on Ubuntu 14.04.

sq006wqa01:/usr/bin# export UNOPATH=/usr/bin/libreoffice
sq006wqa01:/usr/bin# echo $UNOPATH
/usr/bin/libreoffice
sq006wqa01:/usr/bin# unoconv -vvv --show
unoconv: Cannot find a suitable pyuno library and python binary combination in /usr/lib/libreoffice
ERROR: No module named uno

unoconv: Cannot find a suitable office installation on your system.
ERROR: Please locate your office installation and send your feedback to:
       http://github.com/dagwieers/unoconv/issues

**Comment by 0rdinatus** [comment]
@sTb1337 Replace first line to `#!/usr/bin/env python3` or set default `alias python='/usr/bin/python3'`

**Comment by sTb1337** [comment]
@0rdinatus Thanks a lot it worked!

**Comment by SainteCelery** [comment]
This bug from 2012 is still a problem. Is there a fix in progress?

**Comment by mdkhaledben** [comment]
I am facing the same problem on Ubuntu 18.04 in case of $unoconv --show.

My Libreoffice version: Version: 6.0.3.2
                                     Build ID: 1:6.0.3-0ubuntu1

Installed Unoconv package from Repository, version 0.7-1.1

Shebang "#!/usr/bin/env python3" is already exists on "/usr/bin/unoconv" file.

Any known fix or suggestion? Thanks

**Comment by stas00** [comment]
This fixes the problem for me: edit the first line of `/usr/bin/unoconv` to replace:

    #!/usr/bin/env python3

with 

    #!/usr/bin/python3

I found this fix [here](https://github.com/dagwieers/unoconv/issues/405#issuecomment-352429704)

**Comment by regebro** [comment]
I've noticed that when these issues arise, the solution is to run unoconv with the python executable that comes with the Libreoffice installation you want to use. Like so:

```
UNOPATH=/path/to/Libreoffice /path/to/Libreoffice/program/python /usr/bin/unoconv ....
```
Yes, that's fairly annoying, but only happens with multiple LibreOffice and/or Python installations.

**Comment by mohammedyunus009** [comment]
I tried this [solution](https://github.com/unoconv/unoconv/issues/49#issuecomment-5276596) u just need to add in ur terminal `URE_BOOTSTRAP=vnd.sun.star.pathname:/usr/lib64/libreoffice/program/fundamentalrc
UNO_PATH=/usr/lib64/libreoffice/program
PATH=/usr/lib64/libreoffice/program:/home/graaff/bin:/usr/local/bin:/usr/bin:/bin:/opt/bin:/usr/x86_64-pc-linux-gnu/gcc-bin/4.5.3:/opt/android-sdk-update-manager/tools:/opt/android-sdk-update-manager/platform-tools:/usr/games/bin` , Or even UNO_PATH and PATH would work

**Comment by speedplane** [comment]
Here's a one liner that [implements the posted fix above](https://github.com/unoconv/unoconv/issues/49#issuecomment-416317222):

```
sed -i 's|#!/usr/bin/env python3|#!/usr/bin/python3|' /usr/bin/unoconv
```

**Comment by jdhao** [comment]
@speedplane thanks for your solution. Works for me.

**Comment by regebro** [comment]
To find which Python to use to run unoconv, you can try a script I made.

"""
cd /tmp
wget -l https://gist.githubusercontent.com/regebro/036da022dc7d5241a0ee97efdf1458eb/raw/1bc0655423d196acd79a5d9fa60d2baada8dd534/find_uno.py
python3 find_uno.py
"""

It should list all Pythons that have a Libreoffice installed.
