### ISSUE TITLE
unoconv freezes when sending multiple requests to a single listener, after some time

### ISSUE THREAD

**Issue by thilux** [unoconv/unoconv#508]
After processing quite a huge number of requests for converting doc to pdf, connecting to  single unoconv listener, after a while, clients (unoconv connecting to that one listener start to hang).

unoconv 0.8.2
Written by Dag Wieers dag@wieers.com
Homepage at http://dag.wieers.com/home-made/unoconv/

platform posix/linux
python 3.6.8 (default, Apr 8 2019, 18:17:52)
[GCC 8.3.0]
LibreOffice 6.1.4.2

Scenario:

I am running a unoconv listener and having 10 simultaneous users make requests using unoconv using the port of the listener. It goes pretty well, but when I reach the 8th round of each user, it gets stuck. If I add additional users, though, they still can process (always using the single listener) just fine.

Please let me know should additional information be required.

**Comment by regebro** [comment]
I'll have to sadly conclude that this probably means you shouldn't connect more than one client to one listener.
I haven't tried it, and I'd love it to work, but if it doesn't, that's a LibreOffice issue, and nothing we can do anything about.
You probably need to implement a queue of some sort...
