### ISSUE TITLE
You can help Unoconv!

### ISSUE THREAD

**Issue by regebro** [unoconv/unoconv#511]
Open Source is a lot of work, and the more people that help, the better.
Unoconv is looking for help on all levels. We need every kind of person:

* Those that can help answering questions and issues.
* Python programmers that can help fix bugs and add features.
* Libreoffice experts that can explain behaviors and investigate bugs.
* People with ideas of how to improve Unoconv.
* People running on all kinds of various operating systems and Unix distros to replicate bugs.

I can offer you:

* Commit access (i.e. commit and merge, bug-triage, release-management)
* The satisfaction of helping people and contributing to Open Source
* A way to guide the decision process and direction unoconv is going

Comment here or email me at regebro@gmail.com!

**Comment by m1waterman88** [comment]
Still looking for help? I'm looking to give back to the projects that have helped me. I've also been wanting to get involved more in the open-source world. While I can't guarantee any specific amount of time, I'd love to assist when possible.

**Comment by m1waterman88** [comment]
Hey! Reaching back out. Hoping to contribute if possible. Also, I wrote a conversion script in Python for work using unoconv, and I'm hoping this project is still actively maintained. I see there hasn't been a recent commit (more than a year).

**Comment by regebro** [comment]
Yes, we are still looking for help. I'm beginning to think we should start telling people not to start using it, though. But I don't know of any replacement either, so...

**Comment by m1waterman88** [comment]
Is it just a lack of maintenance resources causing you to lean that way, or do you think it should be deprecated anyway? If it needs to be deprecated and a replacement is needed, perhaps that's a project I can look into, which would take some time and care.

If this project persists, I can try to make time to assist with Python bug hunting and features. And try to close out some issues/answer questions (the less sexy but necessary part).

**Comment by regebro** [comment]
The code is messy, I guess it grew from a small script to a very big one over time. Something that is a proper Python module would probably be a lot more readable and maintainable.

Any help, rewriting from scratch or answering issues or fixing bugs is welcome.

**Comment by m1waterman88** [comment]
Excellent. I'll clone the repo and review the code soon.

**Comment by m1waterman88** [comment]
Okay, I'm seeing what you mean. I'm going to focus on obvious readability inhibitors and PEP8 issues first so I can get a better handle on the logic.

**Comment by DaveMellor** [comment]
Goodbye.

**Comment by regebro** [comment]
Hello.

**Comment by kulasinghe** [comment]
I have tried unoconv with moodle. it was successfull. but I need to run it in a separate server to minimize the load on webserver. I configured separate server with centos 8 and libreoffice, unoconv is also works fine in new server. But once i point webserver unoconv to use new server it doesn't work. Could you please help me on pointing to separate server to get conversion process ...

Thanks in advance

**Comment by regebro** [comment]
There is now [Unoserver](https://github.com/unoconv/unoserver), which we are using successfully in production, with fewer bugs as a result.

It can need help instead, it certainly lacks some of Unoconv's features. But Unoconv will likely get a final release, and then get deprecated.
