### ISSUE TITLE
Cannot use unoconv in django celery task

### ISSUE THREAD

**Issue by david-young-fax** [unoconv/unoconv#512]
I can use unoconv in python shell and command line on Ubuntu. 

However, when I try to run it in django celery task (using os.system("unoconv -d document xxx.docx") to execute), it always failed.

I saw that it's recommended to use libreoffice python to run. But where is the libreoffice python?? I installed libreoffice but cannot find it. 

It's quite confusing... could you help?

**Comment by david-young-fax** [comment]
it throws this exception

Fatal Python error: Py_Initialize: Unable to get the locale encoding
  File "/home/ubuntu/env/lib/python2.7/encodings/__init__.py", line 123
    raise CodecRegistryError,\
                            ^
SyntaxError: invalid syntax

**Comment by regebro** [comment]
It sounds like you are trying to run a Python 2 install of unoconv with Python 3...
