### ISSUE TITLE
xlsm format

### ISSUE THREAD

**Issue by alpha-and-omega** [unoconv/unoconv#515]
Hello.
soffice supports xlsm format but unoconv not. Please add it to the list of supported formats.

`fmts.add('spreadsheet', 'xlsx', 'xlsm', '........', '..........')`

**Comment by regebro** [comment]
The new rewrite, https://github.com/unoconv/unoserver/ , doesn't suffer from this maintenance problem, but instead asks Libreoffice for formats, so it should support xlsm. If you could try it that would be awesome.
