### ISSUE TITLE
Install unoconv to amazonlinux for using in AWS Lambda

### ISSUE THREAD

**Issue by LLDmitry** [unoconv/unoconv#517]
Hello, 
is it possible to install and use the unoconv in AWS Lambda? I've got error "No package unoconv available." on command "yum install -y unoconv" from amazonlinux.

**Comment by m1waterman88** [comment]
Hi,

I'm not familiar with amazonlinux, but if it's not in your distro's repo, you can get it from pypi: https://pypi.org/project/unoconv/.

```
python3 -m pip install unoconv
```
