### ISSUE TITLE
Period in output filename ignored

### ISSUE THREAD

**Issue by Andrea-Arguello** [unoconv/unoconv#521]
## Problem
Running the following command
``unoconv -f pdf -o tmp.file tmp.file.doc``
saves the pdf as tmp.pdf

## Expected result
tmp.file.pdf

**Comment by m1waterman88** [comment]
Hey, can you you provide some more information? Is the original file tmp.file or tmp.file.doc?

**Comment by Andrea-Arguello** [comment]
The original file is tmp.file.doc

**Comment by m1waterman88** [comment]
I just tested on my end. These worked for me. Try 'em out and let me know. I don't suggest the third option since it's repetitive, but it works.

unoconv -f pdf tmp.file.doc
unoconv -o tmp.file.pdf tmp.file.doc
unoconv -f pdf -o tmp.file.pdf tmp.file.doc

**Comment by Andrea-Arguello** [comment]
These appear to be working now. May have been a mistake on my end back when I posted the issue. Thanks.
