### ISSUE TITLE
During handling of the above exception, another exception occurred.

### ISSUE THREAD

**Issue by deragon** [unoconv/unoconv#522]
This bug issue is not about the root cause of the problem (root cause is that unoconv detects the input file as an Impress file while it actually is a Draw file).

This bug report is about an error in the error handling code.  I noticed that in many issues reported here in GitHub, this error occurs often but has never been fixed.  A bug in the error handling code causes another exception to be raised, preventing the user to get the proper error showing.

Hopefully, this annoying bug can be fixed easily so the actual error can be shown to the user.

This problem has been reproduced on 2019-12-10 07:50:29 EST, branch release-0.8, with 'unoconv' modified to use 'python3' on the first line instead of 'python'.

```
$ ./unoconv -vvv --format=pdf unoconv-bug.odg 
Verbosity set to level 3
Using office base path: /usr/lib/libreoffice
Using office binary path: /usr/lib/libreoffice/program
DEBUG: Connection type: socket,host=127.0.0.1,port=2002,tcpNoDelay=1;urp;StarOffice.ComponentContext
Input file: unoconv-bug.odg
Selected output format: Portable Document Format [.pdf]
Selected office filter: impress_pdf_Export
Used doctype: presentation
Output file: file:///tmp/unoconv-bug.pdf
Traceback (most recent call last):
  File "/vol/data/base/software/nodist/noarch/unoconv/unoconv", line 1118, in convert
    document.storeToURL(outputurl, tuple(outputprops) )
uno.IOException: SfxBaseModel::impl_store <file:///tmp/unoconv-bug.pdf> failed: 0x81a(Error Area:Io Class:Parameter Code:26)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/vol/data/base/software/nodist/noarch/unoconv/unoconv", line 1389, in <module>
    main()
  File "/vol/data/base/software/nodist/noarch/unoconv/unoconv", line 1305, in main
    convertor.convert(inputfn)
  File "/vol/data/base/software/nodist/noarch/unoconv/unoconv", line 1120, in convert
    raise UnoException("Unable to store document to %s (ErrCode %d)\n\nProperties: %s" % (outputurl, e.ErrCode, outputprops), None)
  File "/usr/lib/python3/dist-packages/uno.py", line 516, in _uno_struct__getattr__
    return getattr(self.__dict__["value"], name)
AttributeError: ErrCode
```

**Comment by regebro** [comment]
Those errors are basically the same: It couldn't write to the file. And you get both errors listed, so I don't see the problem. This is expected and desired behavior.

**Comment by deragon** [comment]
While it seams to try to write to `file:///tmp/unoconv-bug.pdf`, how can we be sure of this?  The actual error is not shown.  It could be an array overflow that was hidden by the AttributeError: ErrCode, nothing to do with the file.file:///tmp/unoconv-bug.pdf.

I believe that this bug should be reopened if since, the code handling the error has not been changed.
