### ISSUE TITLE
unoconv: Cannot find a suitable pyuno library and python binary combination in /usr/lib/libreoffice ERROR: No module named 'uno'

### ISSUE THREAD

**Issue by ihzanat** [unoconv/unoconv#524]
This works perfect via terminal. but in django, it seems error like this. how can this happen ?

**Comment by yasenstar** [comment]
Same issue at Ubuntu

**Comment by Jukoo** [comment]
I have the same  error on MX  Linux

**Comment by m1waterman88** [comment]
I'd venture to say your Django instance is in a venv and looking at its own interpreter. Or are you calling the interpreter provided in the office instance?

**Comment by m1waterman88** [comment]
Did anyone try the suggestions in the README.adoc and still have this issue?

**Comment by m1waterman88** [comment]
Closing issue. There is insufficient information, and there hasn't been a response. It's likely that the venv is preventing unoconv from communicating with the necessary libraries on the system.

**Comment by ihzanat** [comment]
Please excuse me for not following this thread. The problem was actually about the file path I wanted to convert. Initially I tried to load the path from the file input, which loads the project related path instead of the absolute path, which caused an error. After I changed the path to the absolute path, the conversion was successful.
