### ISSUE TITLE
ASCII character xF8 seems to cause missing signs converting txt to pdf

### ISSUE THREAD

**Issue by ero09** [unoconv/unoconv#525]
Hi,

on a RaspberryPi with the newest raspbian distribution I`m not able to convert a textfile to pdf properly using unoconv. LibreOffice version is 6.5.1.2, unoconv version 0.7, python 3.7.3

The textfile is generated by logging an external device via usb. It contains the ASCII character xF8 wich means according to codepage 437 or IBM850 a degree sign. Therefore I'm using import filter:
```  
unoconv -f pdf -i FilterOptions=4 /home/pi/DAC-Logs/test/*.log 
```
Unfortunatly all signs between the first and second occurence of xF8 are missing in the pdf (and the third and forth etc.), as you can see in the attached picture. 
Starting LibreOffice Writer, opening the log-file as 'text -choose encoding' and exporting as pdf works fine. 

For purpose of reproducing, I've attached the textfile 

Any idea to fix the problem? 

Thanks in advance
Egbert Rodeck

[2019-12-29.log](https://github.com/unoconv/unoconv/files/4050902/2019-12-29.log)

![Clipboard](https://user-images.githubusercontent.com/59799340/72223074-96714580-356b-11ea-865c-031b2c1f4274.gif)

**Comment by strichter** [comment]
This sounds like a LibreOffice issue, not a unoconv one.

**Comment by regebro** [comment]
Closing for lack of feeback.
