### ISSUE TITLE
[PDF Export] Missing bookmarks and links only with unoconv

### ISSUE THREAD

**Issue by NicolasGoeddel** [unoconv/unoconv#529]
Hi there,

we are converting huge ODT files up to 3000 pages to PDF. And because these ODTs can contain up to 25,000 bookmarks (`<text:bookmark>`) and even more bookmark references (`<text:bookmark-ref>`) it seems that not all of them are getting included in the resulting PDF file.

It is also not totally deterministic. Sometimes bookmark references are not working from page 1000+, sometimes it begins a bit later or even before page 1000. But then there also can be later pages where the bookmarks work again.

We are using Libreoffice 6.3.4.2 on an Ubuntu 18.04.4 LTS inside a LXC container. The call to the `unoconv` script looks like this:
```
unoconv --port 10000 -f pdf -e IsSkipEmptyPages=false -e ExportBookmarks=true -e ExportBookmarksToPDFDestination=true -e OpenBookmarkLevels=1 -e PageLayout=3 -e -u file:///tmp/libreoffice_port10000 -o /tmp/tmpWjm42C.pdf /tmp/IJ6gOJ.odt
```
I used a modified unoconv script also containing the changes I mentioned [here](https://github.com/unoconv/unoconv/issues/500) and [here](https://github.com/unoconv/unoconv/issues/225#issuecomment-514236053).

I also tried to export the same ODT to PDF using the GUI on my Linux machine with Ubuntu 19.10 and Libreoffice 6.3.4.2 (the same as on the headless server). This way it works flawlessly. The resulting PDF is correct in all ways. Only with unoconv it does not seem to be right.

I can not make our examples public but I will try to create a similar "Lorem Ipsum" style document.

**Comment by regebro** [comment]
It's tricky when the UI has a different result than unoconv, it's very hard to figure out why.

I have released a much simplified version of unoconv called unoserver, https://github.com/unoconv/unoserver/, I would be much obliged if you tried using that one.

Also, perhaps just try using Libreoffice from the command line directly and see if that makes a difference?

**Comment by regebro** [comment]
Closed due to lack of response.
