### ISSUE TITLE
OS: Alpine dynamic module does not define init function (initpyuno)

### ISSUE THREAD

**Issue by he19920226he** [unoconv/unoconv#535]
unoconv: Cannot find a suitable pyuno library and python binary combination in /usr/lib/libreoffice
ERROR: dynamic module does not define init function (initpyuno)

unoconv: Cannot find a suitable office installation on your system.
ERROR: Please locate your office installation and send your feedback to:
       http://github.com/dagwieers/unoconv/issues

![image](https://user-images.githubusercontent.com/13690842/76150585-1983c780-60e7-11ea-84cf-7ed8804b77ed.png)

**Comment by he19920226he** [comment]
/home/unoconv-0.8.2 # apk list | grep libreoffice
libreoffice-lang-nb-5.4.5.1-r0 x86_64 {libreoffice} (MPL2)
libreoffice-lang-bn_in-5.4.5.1-r0 x86_64 {libreoffice} (MPL2)
libreoffice-lang-sr-5.4.5.1-r0 x86_64 {libreoffice} (MPL2)
libreoffice-lang-om-5.4.5.1-r0 x86_64 {libreoffice} (MPL2)
libreoffice-lang-et-5.4.5.1-r0 x86_64 {libreoffice} (MPL2)
libreoffice-lang-kk-5.4.5.1-r0 x86_64 {libreoffice} (MPL2)
faenza-icon-theme-libreoffice-1.3.1-r4 x86_64 {faenza-icon-theme} (GPL)
libreoffice-lang-ss-5.4.5.1-r0 x86_64 {libreoffice} (MPL2)
libreoffice-lang-ve-5.4.5.1-r0 x86_64 {libreoffice} (MPL2)
libreofficekit-5.4.5.1-r0 x86_64 {libreoffice} (MPL2) [installed]
faenza-icon-theme-libreoffice-common-1.3.1-r4 x86_64 {faenza-icon-theme} (GPL)
libreoffice-lang-th-5.4.5.1-r0 x86_64 {libreoffice} (MPL2)
libreoffice-lang-sat-5.4.5.1-r0 x86_64 {libreoffice} (MPL2)
libreoffice-lang-st-5.4.5.1-r0 x86_64 {libreoffice} (MPL2)
libreoffice-lang-nr-5.4.5.1-r0 x86_64 {libreoffice} (MPL2)
libreoffice-base-5.4.5.1-r0 x86_64 {libreoffice} (MPL2) [installed]
faenza-icon-theme-libreoffice-main-1.3.1-r4 x86_64 {faenza-icon-theme} (GPL)
libreoffice-lang-cy-5.4.5.1-r0 x86_64 {libreoffice} (MPL2)
libreoffice-lang-brx-5.4.5.1-r0 x86_64 {libreoffice} (MPL2)
libreoffice-writer-5.4.5.1-r0 x86_64 {libreoffice} (MPL2) [installed]

**Comment by m1waterman88** [comment]
Check out the [README](https://github.com/unoconv/unoconv/blob/master/README.adoc). If it doesn't resolve the issue, let me know.

**Comment by m1waterman88** [comment]
Closing issue. There is insufficient information, and there hasn't been a response. Typically this error is from either running an illegal command or running unoconv in a venv/container that can't speak with the system. If you have more information, please reply and let me know.
