### ISSUE TITLE
ERROR: No module named 'unohelper'

### ISSUE THREAD

**Issue by MorganTpx** [unoconv/unoconv#537]
`unoconv: Cannot find a suitable pyuno library and python binary combination in /usr/lib/libreoffice
ERROR: No module named 'unohelper'

unoconv: Cannot find a suitable office installation on your system.
ERROR: Please locate your office installation and send your feedback to:
       http://github.com/dagwieers/unoconv/issues
`
my unoconv used python3.6 env

`#!/usr/local/bin/python3.6
  
###
###
### Copyright 2007-2010 Dag Wieers <dag@wieers.com>

from __future__ import print_function

from distutils.version import LooseVersion
import getopt
import glob
import os
import signal
import subprocess
import sys
import time

__version__ = '0.9.0'

doctypes = ('document', 'graphics', 'presentation', 'spreadsheet')

global convertor, office, ooproc, product
ooproc = None
uno = unohelper = None
exitcode = 0
`

please help me ，how can i do it？

**Comment by MorganTpx** [comment]
If i used pip3 install uno  to install  uno  

then  unoconv -vv

show this error
`unoconv: Cannot find a suitable pyuno library and python binary combination in /usr/lib/libreoffice
ERROR: No module named 'base'

unoconv: Cannot find a suitable office installation on your system.
ERROR: Please locate your office installation and send your feedback to:
       http://github.com/dagwieers/unoconv/issues
`

**Comment by m1waterman88** [comment]
A few questions:
- Which OS do you have?
- Which version of python is set at the system level or in the venv if you're using one?
- Is either LibreOffice or OpenOffice installed on your system?
- Did you review the install suggestions in the README?

**Comment by m1waterman88** [comment]
Closing issue. There is insufficient information, and there hasn't been a response.
