### ISSUE TITLE
(b'', b'/Applications/LibreOffice.app/Contents/Resources/python: line 54: /Applications/LibreOffice.app/Contents/Resources/../Frameworks/LibreOfficePython.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/LibreOfficePython: Argument list too long\n/Applications/LibreOffice.app/Contents/Resources/python: line 54: /Applications/LibreOffice.app/Contents/Resources/../Frameworks/LibreOfficePython.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/LibreOfficePython: Undefined error: 0\n')

### ISSUE THREAD

**Issue by yazeed72** [unoconv/unoconv#538]
(b'', b'/Applications/LibreOffice.app/Contents/Resources/python: line 54: /Applications/LibreOffice.app/Contents/Resources/../Frameworks/LibreOfficePython.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/LibreOfficePython: Argument list too long\n/Applications/LibreOffice.app/Contents/Resources/python: line 54: /Applications/LibreOffice.app/Contents/Resources/../Frameworks/LibreOfficePython.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/LibreOfficePython: Undefined error: 0\n')

unoconv 0.9.0
python 3.7 
LibreOffice  6.4.2.2

**Comment by m1waterman88** [comment]
Please provide details. What happened to get this error to occur?

**Comment by digitalkaoz** [comment]
got the same error here on OSX:

```
unoconv -e PageRange=1-1 -f pdf --stdout SOME.html
```

results in 

```
python: line 54: LibreOfficePython: Argument list too long
python: line 54: LibreOfficePython: Undefined error: 0
```

**Comment by digitalkaoz** [comment]
@yazeed72 why did you closed this issue?
@m1waterman88 does that help?

**Comment by yazeed72** [comment]
I end up using Linux instead of using macOS x
