### ISSUE TITLE
Docx to PDF Issue on Cent OS 7 

### ISSUE THREAD

**Issue by chppatel** [unoconv/unoconv#539]
We are trying to convert a docx file on Centos 7.

> unoconv 0.8.2
> Written by Dag Wieers <dag@wieers.com>
> Homepage at http://dag.wieers.com/home-made/unoconv/
> 
> platform posix/linux2
> python 2.7.5 (default, Aug  7 2019, 00:51:29)
> [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
> LibreOffice 5.3.6.1
> 

Gives us this error

```
unoconv: RuntimeException during import phase:
Office probably died. Unsupported URL <file:///......../filename.docx>: "type detection failed"

```

Maybe this is because we are using LibreOffice 5.3 and not 6 perhaps?

**Comment by m1waterman88** [comment]
Please provide the command you used to generate the error. Also explicitly let me know the name of the current file and desired file.

**Comment by m1waterman88** [comment]
Closing issue. There is insufficient information, and there hasn't been a response.
