### ISSUE TITLE
Possibility to set pdf title specified in unoconv parameter

### ISSUE THREAD

**Issue by janmottl** [unoconv/unoconv#540]
Is there a possibility to set pdf title specified in unoconv parameter? Thanks

**Comment by m1waterman88** [comment]
I think you're asking to change the base filename in addition to the extension. If so, yes. Example:

```
$ ls
hi.txt
$ unoconv -o hello.pdf hi.txt
$ ls
hello.pdf  hi.txt
```

If not, please clarify and I'll see if I can help.

**Comment by janmottl** [comment]
I'm searching a solution how to set title in pdf properties

![image](https://user-images.githubusercontent.com/18611287/81296729-a0670900-9072-11ea-8e11-21be42e9ace8.png)

**Comment by m1waterman88** [comment]
No, unfortunately you can't update PDF metadate with unoconv. In fact, reading PDFs with Python can be patchy in general.
