### ISSUE TITLE
Calling unoconv using runpy provoke the expiration of the rest of the script

### ISSUE THREAD

**Issue by exodehm** [unoconv/unoconv#541]
Consider this code:
```
import runpy
import sys

sys.argv = ['','-f','pdf','dummy.odt']
runpy.run_path('/usr/bin/unoconv', run_name='__main__')
print ("do someting more...")
```

The script finishes after the call to unoconv from runpy and the print command doesn't execute.

I can call unoconv using subprocess:
`subprocess.call(('unoconv', '-f', 'pdf', 'dummy.odt')`

And the scripts continues after the call to runpy, but I prefer the first method and I wonder the cause of this behavior.

**Comment by m1waterman88** [comment]
It seems that unoconv is running properly, and although the Pythonista in me wants to research this with you anyway, I'm a bit pressed and it's outside this repository's scope.
