### ISSUE TITLE
Problems converting html to fodt on Windows

### ISSUE THREAD

**Issue by apscekdm** [unoconv/unoconv#543]
Hello,

I'm developing a small cross-platform application (under the GPL v3 license) and I recently implemented a conversion function to the ODT format, which is managed by LibreOffice (soffice), it works very well under GNU/Linux and MacOS. Under Windows it's different ..., so I turned to unoconv. Nevertheless I have problems with accented characters under Windows (which is not the case with Unoconv tests under GNU/Linux).

Here's the conversion command executed by the conversion function in my software in Windows seven :

`"C:\Program Files\LibreOffice\program\python.exe" C:\Users\LENOVO~1\AppData\Local\Temp\_MEI7682\unoconv_apsc\unoconv -o C:/angelo/a1a1.fodt -f fodt C:\Users\LENOVO~1\AppData\Local\Temp\data_html_apsc_ficheo6_jsz27.html`

[Here's the result](https://laginette.com/apsc/tests/a1a1.fodt) (we see the problems with the accented characters).

Here's the information concerning the system (Windows 7), the Python version of LibreOffice and the version of LibreOffice:

`C:\Windows\System32>"C:\Program Files\LibreOffice\program\python.exe" C:\angelo\
projet_APSC_py3_pyqt5_Windows_DEV_CASSE\unoconv_apsc\unoconv --version
unoconv 0.9.0
Written by Dag Wieers <dag@wieers.com>
Homepage at http://dag.wieers.com/home-made/unoconv/

platform nt/win32
python 3.5.5 (default, Jan 31 2019, 00:04:27) [MSC v.1900 64 bit (AMD64)]
LibreOffice 6.1.5.2

C:\Windows\System32>`

Problem that I don't encounter under GNU/Linux (however with an earlier version of LibreOffice), the command I tested:

`angelo@angelo-kubuntu:~/projet_APSC_py3_pyqt5_DEV_CASSE$ python3 /home/angelo/projet_APSC_py3_pyqt5_DEV_CASSE/unoconv_apsc/unoconv -o /home/angelo/a1a1_test_sous_gnu_linux.odt -f fodt /home/angelo/data_html_apsc_fiche.html`

... [and the result](https://laginette.com/apsc/tests/a1a1_test_sous_gnu_linux.fodt) (no problem with accented characters).

Here's the information concerning the system (Kubuntu 18.04), the Python version of LibreOffice and the version of LibreOffice:

`angelo@angelo-kubuntu:~/projet_APSC_py3_pyqt5_DEV_CASSE$ python3 /home/angelo/projet_APSC_py3_pyqt5_DEV_CASSE/unoconv_apsc/unoconv --version
unoconv 0.9.0
Written by Dag Wieers <dag@wieers.com>
Homepage at http://dag.wieers.com/home-made/unoconv/

platform posix/linux
python 3.6.9 (default, Apr 18 2020, 01:56:04) 
[GCC 8.4.0]
LibreOffice 6.0.7.3`

Additional information:

`angelo@angelo-kubuntu:~$ uname -a
Linux angelo-kubuntu 5.3.0-51-generic #44~18.04.2-Ubuntu SMP Thu Apr 23 14:27:18 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

Can you help me fix these conversion and accented character issues (HTML to FODT) on Windows with Unoconv?

Is this due to the version of LibreOffice installed under Windows?, if so why don't I have this same problem under GNU/Linux?

Excuse-me for my bad english.

See you soon.

**Comment by regebro** [comment]
If it's the exact same file, I can only assume Libreoffice opens the file with a windows encoding on windows.
Is the encoding specified in the HTML file?

**Comment by regebro** [comment]
Closed due to lack of response.
