### ISSUE TITLE
jpg != jpg? Some pictures with problems...

### ISSUE THREAD

**Issue by white-rabbit07** [unoconv/unoconv#544]
Hi. 
We installed unoconv to use it with moodle. Users are able to upload their pictures from their smartphones directly to moodle where unoconv should convert them into PDF-Files. Most of the time this works well but some pictures won't be converted. Here are some examples:

moodle simply says "undefined":
`file 15892733232091045619170125136810.jpg 
15892733232091045619170125136810.jpg: JPEG image data, Exif standard: [TIFF image data, little-endian, direntries=12, height=3096, manufacturer=samsung, model=SM-A202F, orientation=upper-right, xresolution=210, yresolution=218, resolutionunit=2, software=A202FXXU3BTD1, datetime=2020:05:12 10:49:43, width=4128], baseline, precision 8, 4128x3096, frames 3`

This picture didn't work either:
`file 1A93B236-ACB0-45AE-BAEB-A6F4907B26B1.jpeg 
1A93B236-ACB0-45AE-BAEB-A6F4907B26B1.jpeg: JPEG image data, Exif standard: [TIFF image data, big-endian, direntries=10, manufacturer=Apple, model=iPhone 6, orientation=upper-right, xresolution=150, yresolution=158, resolutionunit=2, software=12.4.5, datetime=2020:04:19 11:01:07], baseline, precision 8, 3264x2448, frames 3`

But this one worked (like most of the other files):
`file Mathe1.jpg 
Mathe1.jpg: JPEG image data, Exif standard: [TIFF image data, big-endian, direntries=12, model=SM-A405FN, height=0, software=A405FNXXU3BTC4, orientation=[*0*], datetime=2020:05:12 16:37:02, resolutionunit=2, xresolution=203, yresolution=211, manufacturer=samsung, width=0], baseline, precision 8, 3886x2423, frames 3`

So, what's the problem here? Is the long filename a problem or is it something else?
Thanks.

**Comment by mwchambers** [comment]
FYI - This may be related: https://moodle.org/mod/forum/discuss.php?d=375660#p1514928

**Comment by nadavkav** [comment]
I also experience issues trying to convert jpeg files to pdf. (In Moodle 3.9)
jpg to pdf works fine.
