### ISSUE TITLE
Preventing memory leaking

### ISSUE THREAD

**Issue by woodholly** [unoconv/unoconv#545]
Hello guys.
soffice.bin started by unoconv --listener eats more and more memory with time and with increasing number of processed documents.
I want to prevent it and restart soffice.bin when it eats more than 1G and not usable by clients.
Is it possible ?

**Comment by steevepay** [comment]
I got the same issue, any news on this?

**Comment by adamaiken89** [comment]
Same issue on 10th Dec 2020.

**Comment by regebro** [comment]
No news, we don't have the same issue.

We've started on a new software with simpler codebase to maybe someday replace unoconv. It's called unoserver.

https://github.com/unoconv/unoserver

The first usable beta is now out. If anyone would like to try it and see if it possibly improves the issue, that would be great.
It could even be worse, this is just fresh out and needs testing.

**Comment by regebro** [comment]
If no one is willing to try it out, this can't be an issue any more.
