### ISSUE TITLE
DOCX to PDF - Output of custom styles broken / empty

### ISSUE THREAD

**Issue by THenkeDE** [unoconv/unoconv#547]
When i convert a docx with custom styles and links, unoconv will simply ignore the content and leave the area blank.

If i convert the very same document with the soffice binary directly, everything is there and in good working shape.

Source-File: [test.docx](https://github.com/unoconv/unoconv/files/4668105/test.docx)

I used these commandlines:

`unoconv -f pdf -e IsSkipEmptyPages=false -e ExportBookmarks=true -e ExportBookmarksToPDFDestination=true /tmp/test.docx`

Resulting file: [test_with_unoconv.pdf](https://github.com/unoconv/unoconv/files/4668107/test_with_unoconv.pdf)

`soffice --headless --convert-to pdf --outdir /tmp/ /tmp/test.docx`

Resulting file: [test_with_soffice.pdf](https://github.com/unoconv/unoconv/files/4668106/test_with_soffice.pdf)

Is it me doing something wrong? I was unable to find anything about this.

**Comment by regebro** [comment]
I'm happy to report that using  https://github.com/unoconv/unoserver worked in this case, if you need to use LibreOffice as a deamon. Otherwise just calling soffice directly is better.
