### ISSUE TITLE
[Ubuntu 20].(ppt|pptx|xls|xlsx) -> pdf conversion failed

### ISSUE THREAD

**Issue by kptLucek** [unoconv/unoconv#548]
Hi there

I'm facing an issue with converting an documents to pdf.

**Source files tested**:
https://file-examples.com/index.php/sample-documents-download/sample-xls-download/
```
670 kB | 5000 rows | xls
184 kB | 5000 rows | xlsx
```
https://file-examples.com/index.php/sample-documents-download/sample-ppt-file/
```
1 MB ppt
```

command line:
```
unoconv -d document -f pdf document.ppt
```

**Issue description**:
I have downloaded files from above, and ran command as mentioned, result is **command runs already for over 30min, there's no output**, however **once prcocess got killed, the result file appears (but not always), and it's over 3000 pages pdf with unknown characters on each page**.

**Lib version**
```bash
$ unoconv --version
unoconv 0.7
Written by Dag Wieers <dag@wieers.com>
Homepage at http://dag.wieers.com/home-made/unoconv/

platform posix/linux
python 3.8.2 (default, Apr 27 2020, 15:53:34) 
[GCC 9.3.0]
LibreOffice 6.4.3.2
```
```bash
$ java --version
openjdk 11.0.7 2020-04-14
OpenJDK Runtime Environment (build 11.0.7+10-post-Ubuntu-3ubuntu1)
OpenJDK 64-Bit Server VM (build 11.0.7+10-post-Ubuntu-3ubuntu1, mixed mode, sharing)
```

Thanks for assistance

**Comment by regebro** [comment]
I get this with `libreoffice TestFiles/file_example_PPT_250kB.ppt --convert-to pdf` , which means this isn't an Unoconv issue, it's a Libreoffice issue.
