### ISSUE TITLE
Arabic Text Causes an Error – Error: source file could not be loaded

### ISSUE THREAD

**Issue by Enijar** [unoconv/unoconv#549]
Appologies if this is not the correct place to write this issue, as I'm 90% certain this is an issue with libreoffice. I'm hoping someone who has solved this issue will see this and share a solution with others who have run into the same issue.

### The Issue

I have two files [en.docx](https://accession-health.s3.eu-west-2.amazonaws.com/test/en.docx) and [ar.docx](https://accession-health.s3.eu-west-2.amazonaws.com/test/ar.docx). Both files contain the same formatting and content. The only difference between the two is that ar.docx contains a small paragraph of right-to-left arabic text.

Converting en.docx to HTML works fine with:

```shell
soffice --headless --convert-to html:HTML:EmbedImages en.docx
```

When I try to convert ar.docx to HTML I get this error:

```
func=xmlSecCheckVersionExt:file=xmlsec.c:line=188:obj=unknown:subj=unknown:error=19:invalid version:mode=abi compatible;expected minor version=2;real minor version=2;expected subminor version=25;real subminor version=26
Error: source file could not be loaded
```

My assumption is that Arabic text is not supported in libreoffice. If this is the case, does anyone know of a potential work around for this? For example stripping arabic text, or re-encoding the docx file with a different format?

Any help would be greately appreciated 👍 

### Reproducable Docker Example

This sets up an Ubuntu 18.04 container with `unoconv` and `libreoffice` installed.

Save this to a Dockerfile file:

```docker
FROM ubuntu:18.04
RUN apt-get update --fix-missing && apt-get install -y apt-transport-https
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y unoconv libreoffice
```

Setup, build, run, and reproduce this error:

```shell
# Download example files
curl https://accession-health.s3.eu-west-2.amazonaws.com/test/en.docx -o en.docx # working example
curl https://accession-health.s3.eu-west-2.amazonaws.com/test/en.docx -o ar.docx # failing example

# Build and run container
docker build -t doc-converter .
docker run -v "$(pwd)":/app -it doc-converter

# Inside the container
cd /app
soffice --headless --convert-to html:HTML:EmbedImages /app/ar.docx
```

**Comment by regebro** [comment]
Yes, this is a LibreOffice issue, nothing unoconv can do anything about.
