### ISSUE TITLE
ImportError: No module named 'com' (or 'com.sun.star.document.UpdateDocMode.NO_UPDATE' is unknown)

### ISSUE THREAD

**Issue by triffid** [unoconv/unoconv#551]
Running unoconv 0.9.0 and libreoffice 6.4.6.2 on Gentoo Linux with python 3.7.

Full output:

```
$ unoconv
Traceback (most recent call last):
File "/usr/bin/unoconv", line 1397, in <module>
from com.sun.star.document.UpdateDocMode import NO_UPDATE, QUIET_UPDATE
File "/usr/lib/python3.7/site-packages/uno.py", line 436, in _uno_import
raise uno_import_exc
File "/usr/lib/python3.7/site-packages/uno.py", line 358, in _uno_import
return _builtin_import(name, *optargs, **kwargs)
ImportError: No module named 'com' (or 'com.sun.star.document.UpdateDocMode.NO_UPDATE' is unknown)
```

There's no running open/libreoffice, there's no stray lock files, `$ python -c 'import uno, unohelper'` silently succeeds, and manually converting the document with libreoffice works perfectly.

#258, #348 seem related but in this case it's complaining about `NO_UPDATE` rather than `QUIET_UPDATE`.

My libreoffice doesn't have its own python interpreter so I can't try running under it as suggested in those issues:
```
$ ls -l /usr/lib64/libreoffice/program/python*
-rw-r--r-- 1 root root 6.7K Aug  7 01:51 /usr/lib64/libreoffice/program/pythonloader.py
-rw-r--r-- 1 root root   44 Aug 21 02:48 /usr/lib64/libreoffice/program/pythonloader.unorc
-rw-r--r-- 1 root root  43K Aug  7 01:51 /usr/lib64/libreoffice/program/pythonscript.py
```

I'm happy to generate more extensive debug logs, just let me know what you need.

**Comment by Sembiance** [comment]
I see the same problem on Gentoo with libreoffice 6.4.6.2 

Note: Downgrading libreoffice to 6.4.5.2 fixes the problem.
So my guess is unoconv doesn't support 6.4.6.2 yet.

**Comment by triffid** [comment]
@Sembiance https://bugs.gentoo.org/741478 if you want to jump in there and note that you're also affected

**Comment by akhuettel** [comment]
This is not a problem with unoconv I think. More info soon.

**Comment by akhuettel** [comment]
Gentoo LibreOffice maintainer here. This report can be closed. The problem is Gentoo-specific (and in our libreoffice installation).

[Gentoo modifies uno.py on install and with the latest version something went wrong there. Which seems to only affect unoconv and produce this rather strange error. I'll fix it tomorrow, after catching some sleep.]
