### ISSUE TITLE
unoconv

### ISSUE THREAD

**Issue by MervinJarvis** [unoconv/unoconv#552]
while trying convert using  unoconv -f xls dose.html

I get this error
unoconv: Cannot find a suitable pyuno library and python binary combination in /usr/lib/libreoffice
ERROR: No module named uno

unoconv: Cannot find a suitable office installation on your system.
ERROR: Please locate your office installation and send your feedback to:
       http://github.com/dagwieers/unoconv/issues

**Comment by regebro** [comment]
This is a duplicate of #49
