### ISSUE TITLE
Unoconv do not convert mathtype

### ISSUE THREAD

**Issue by Pitoucol** [unoconv/unoconv#553]
Hello

We are using unoconv in Moodle.
Students can use Mathtype through the grade text editor activity.

On teacher side, unconv converts this answer into pdf : correct.
But unoconv do not convert mathtype, the mathtype answer is even not readable, replaced by unreadable code, as seen in the attachment.

can you do something with that ?
thank you.

![Moodle_Editeur_ConversionPDF](https://user-images.githubusercontent.com/70409859/91610037-ccd3c780-e978-11ea-8a67-e1db09fb4c10.jpg)

**Comment by regebro** [comment]
- Will it export it correctly if you just Export to PDF from libreoffice?
- How does running `libreoffice <filename> --convert-to pdf` work?
