### ISSUE TITLE
Convert *.docx to pdf missing first file

### ISSUE THREAD

**Issue by aBahrami13** [unoconv/unoconv#555]
**System Info:**
unoconv 0.7
platform posix/linux -> ubuntu 18.04
python 3.5.2 (default, Jul 17 2020, 14:04:10)
[GCC 5.4.0 20160609]
LibreOffice 5.1.6.2

**Steps to generate error:**
1) List all directory contents using `ls` command, result is:
`b.docx c.docx d.docx`

2) Run `sudo /usr/bin/unoconv --server localhost --port 2002 -f pdf -t *.docx`

**Expected result:**
All docx files should be converted to pdf & if run `ls` command, the following output should be shown:
`b.docx b.pdf c.docx c.pdf d.docx d.pdf`

**Actual result:**
The first file is skipped!
Result of `ls` command is:
`b.docx c.docx c.pdf d.docx d.pdf`

**Comment by regebro** [comment]
Yes, because -t takes a template parameter, so the first file is used as a template. Skip the -t and it should work.
