### ISSUE TITLE
Outdated docs, dead links on export filters

### ISSUE THREAD

**Issue by jscott0** [unoconv/unoconv#556]
Looking at some of the documentation, it's pretty old and this link about PDF export filters is now dead: https://wiki.openoffice.org/wiki/API/Tutorials/PDF_export

I'd be glad to help if you would know where to find up-to-date information for LibreOffice. In particular, my use case is to digitally sign PDFs made with other software, something which LibreOffice has supported for a little while but is tedious going through the menus. Opening the document read-only and then exporting it in place is basically how LibreOffice does it, so I hope unoconv can help me with this as well.

**Comment by regebro** [comment]
Unfortunately the Libreoffice documentation is pretty bad.

I don't know how you would support digital signatures with unoconv.

**Comment by regebro** [comment]
Closing as it's a Libreoffice documentation problem which we can't fix.
