### ISSUE TITLE
could not open large PPTX file to convert to PDF

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [unoconv/unoconv#557]
Hello,

Tried to convert a 169MB PPTX file in a PDF but unoconv daemon directly rejected it saying "could not be open"
is there any file size limitation? if yes how to increase it?

thanks

**Comment by regebro** [comment]
There shouldn't be a limit except if you run out of memory.

**Comment by ROBERT-MCDOWELL** [comment]
ok thanks, it was something else apparently, don't remember ;)
