### ISSUE TITLE
Unable to convert JPEG, although JPG is supported 

### ISSUE THREAD

**Issue by nadavkav** [unoconv/unoconv#560]
I am a system administrator of a Moodle 3.9 that uses unoconv to convert submitted files that students upload to the assignment activity into PDF files that can be edited and annotated by the teachers, online.

I am reported that unoconv does not support JPEG file extensions, but does support JPG file extension.
Since it is basically the same mimetype, it seems only logical that this can be supported by unoconv. 

unoconv --show
...
jpg      - Joint Photographic Experts Group [.jpg]
...

**Comment by nadavkav** [comment]
FIX:
Editing the unoconv file:
https://github.com/unoconv/unoconv/blob/345a7f9763fc5744327774c2d5356a260b922b14/unoconv#L481
and adding:
fmts.add('graphics', 'jpeg', 'jpeg', 'Joint Photographic Experts Group', 'draw_jpg_Export') 

Solved this issue.

Please see if you can patch it.

**Comment by mputzi** [comment]
#561

**Comment by mara004** [comment]
This solution is kind of "workaroundish" - there might be more file types that can take multiple extensions. What about using [mimetypes](https://docs.python.org/3/library/mimetypes.html) ([specification](https://www.iana.org/assignments/media-types/media-types.xhtml))?
