### ISSUE TITLE
Unoconv + LibreOffice (7.0.3.1) + macOS 11.0.1 (Big Sur) = does not work

### ISSUE THREAD

**Issue by DavidAyliffe** [unoconv/unoconv#562]
Hi Guys

Does anyone have any pointers at how to get this combination to work?
I had a setup running using LO4.something and macOS 10.something and this was fine but since the upgrade to Big Sur, I've had to upgrade to LO 7.

Now nothing works.

When I run
"/Applications/LibreOffice.app/Contents/MacOS/python unoconv -f pdf test.docx"
I get an error:
zsh: no such file or directory: /Applications/LibreOffice.app/Contents/MacOS/python

And when I try to launch unoconv from within a script I get this error:
unoconv: Cannot find a suitable pyuno library and python binary combination in /Applications/LibreOffice.app/Contents
ERROR: No module named uno

unoconv: Cannot find a suitable office installation on your system.
ERROR: Please locate your office installation and send your feedback to:
       http://github.com/dagwieers/unoconv/issues

(Also, how can I see from the command line which version of unoconv I have?)

Does anyone have any ideas?

Thanks
DA

**Comment by FeelmyLife-droid** [comment]
Hi David. Sorry for my bad English, I'm writing through a translator. I myself use BigSure + LO 7. Just try to write "unoconv -h" in the terminal. This works for me.

**Comment by SamuelSwartzberg** [comment]
I installed unoconv and libreoffice via homebrew and everything worked fine for me. I'm not an expert, but if you're still having this problem, it might be related to some of your installations being x86_64 and some being arm-based. Try prefixing your command with arch --x86_64 and seeing if it works!

**Comment by m1waterman88** [comment]
I don't have a Mac, so it's difficult to troubleshoot. The error is stating that "/Applications/LibreOffice.app/Contents/MacOS/python" doesn't exist. Let's start simple. Does it?

**Comment by regebro** [comment]
No reply on this, closing it.
