### ISSUE TITLE
How to specify default font fallback

### ISSUE THREAD

**Issue by Herz3h** [unoconv/unoconv#563]
In case of missing font on the system, Word would choose a specific default font (seems to be Times New Roman in my case). 

Was wondering if there is a way to instruct a default font fallback to libreoffice using unoconv ?

**Comment by regebro** [comment]
That doesn't seem possible with unoconv. But have you tried setting it in LibreOffice? Unoconv should use the same profile, so it might use the same settings in this case?

**Comment by chuxubank** [comment]
I'm facing the same problem.
<img width="959" alt="image" src="https://user-images.githubusercontent.com/17001575/144450779-349f88e8-7ec0-4d2a-b0fa-711dc82bc66b.png">
I've set the replacement table in Libreoffice (as above), and in Libreoffice fonts are looking all good, but the converted picture does not follow the font replacement.

**Comment by chuxubank** [comment]
Sorry for that, previously I'm using Emacs(DocView) to call the unoconv, the font doesn't follow my settings (maybe it calls soffice with some extra settings), when I call unoconv directly from CLI, it works.

**Comment by regebro** [comment]
Great!
