### ISSUE TITLE
Converting PPTX to PDF with Shape on Master Kills Image on Slide

### ISSUE THREAD

**Issue by blitline-dev** [unoconv/unoconv#565]
[example.pptx](https://github.com/unoconv/unoconv/files/5704195/example.pptx)

In the attached example there is a shape on the Master Slide. In the presentation there is an image on Slide #1. Trying to export this to PDF causes the image on Slide #1 to not render.

unoconv -f pdf example.pptx

![example2](https://user-images.githubusercontent.com/1251631/102381809-87b2c000-3f7e-11eb-829a-77b6f526b22a.png)

**Comment by regebro** [comment]
I tried this, and although the output isn't pretty, the image is included...
