### ISSUE TITLE
Encrypting pdf via unoconv

### ISSUE THREAD

**Issue by janmottl** [unoconv/unoconv#569]
I convert an odt document to pdf using unoconv. I need to encrypt resulting pdf file. So I tried to set PDF export filter options. But it doesn't work. Resulting pdf is not encrypted.

unoconv --version

unoconv 0.7 Written by Dag Wieers dag@wieers.com Homepage at http://dag.wieers.com/home-made/unoconv/

platform posix/linux python 3.7.3 (default, Dec 20 2019, 18:57:59) [GCC 8.3.0] LibreOffice 6.1.5.2

./unoconv -f pdf -e EncryptFile=True -e DocumentOpenPassword=1234 -e RestrictPermissionPassword=True -e PermissionPassword=1234 "/data/test/test.odt"

**Comment by regebro** [comment]
Can you encrypt it using LibreOffice directly? What command line do you use then?

**Comment by strichter** [comment]
I am not sure whether unoconv should be used for all the features that LibreOffice supports. Here is a quick Linux command to encrypt the file afterwards:

```
qpdf --encrypt [readpass] [ownerpass] 256 -- [infile].pdf [outfile].pdf
```

**Comment by regebro** [comment]
Closed due to lack of response.
