### ISSUE TITLE
unoconv: RuntimeException during import phase:  Office probably died. Unsupported URL

### ISSUE THREAD

**Issue by JonAnder83** [unoconv/unoconv#570]
I have a machine that tries to call another machine that has a listening unoconv instance.
The client machine tries to get the document processed like so:  unoconv --server=192.168.1.20 --port=2002 "/home/john/testdoc.docx"

And the server machine is listenning for connections with this systemd unit:  unoconv --listener --server 192.168.1.20 --port 2002

For some reason, I always get the same error message: 

``unoconv: RuntimeException during import phase:                                                                                                             │
Office probably died. Unsupported URL <file:///home/john/testdoc.docx>: "type detection failed" /build/libreoffice-hlLbXa/libreoffice-7.1.1~rc2/framework/│
source/loadenv/loadenv.cxx:189``

And I really don't know how to proceed.

Client OS is Ubuntu 18.04
Server OS is Ubuntu 20.04

Both have the official ppa repos for libreoffice and are using both the same official versions

**Comment by regebro** [comment]
This generally means it did not find the file, or it's not a valid docx file.
