### ISSUE TITLE
Error attempting to use unoconv with Libreoffice. Distribution Linux Mint.

### ISSUE THREAD

**Issue by pamindic** [unoconv/unoconv#572]
unoconv -d docx Wand1.odt 
unoconv: Cannot find a suitable pyuno library and python binary combination in /usr/lib/libreoffice
ERROR: No module named uno

unoconv: Cannot find a suitable office installation on your system.
ERROR: Please locate your office installation and send your feedback to:
       http://github.com/dagwieers/unoconv/issues

**Comment by regebro** [comment]
Duplicates #49
