### ISSUE TITLE
Is libreoffice-script-provider-python yet another name variant of UNO python bindings package?

### ISSUE THREAD

**Issue by matkoniecz** [unoconv/unoconv#573]
> A hard requirement is the UNO python bindings which are often inside a subpackage named libreoffice-pyuno or libobasis4.4-pyuno.

Neither is available in Ubuntu 20.04 

Looking at https://askubuntu.com/questions/418225/how-do-i-install-the-python-uno-package and https://packages.ubuntu.com/xenial/libreoffice-script-provider-python I suspect that libreoffice-script-provider-python is their replacement.

Is it true?

**Comment by regebro** [comment]
I use Ubuntu 20.04, and `uno` was installed as a part of LibreOffice, you don't need to install anything extra.
