### ISSUE TITLE
unoconv vs libreoffice headless

### ISSUE THREAD

**Issue by osamagithub80** [unoconv/unoconv#574]
Hello, I have been searching a lot for the right way to use Libreoffice for the purpose of converting word documents to pdf documents from within a php application in windows server. What I found is the following:

1- Simply call libreoffice headless using php “exec” command, for example
soffice --headless --convert-to pdf abc.docx --outdir ./my_files … etc
2- Using unoconv or similar libraries
3- Using "Libreoffice Online" from Collaboraonline

I tried the first approach and it is working fine. So, I’m not sure why should I go with approach 2 or 3. What is the right approach to use? Is it just a matter of convenience? or there are concrete reasons behind which option to use (such as parallel requests, scalability, etc)

**Comment by regebro** [comment]
Use whatever works for you.

**Comment by strichter** [comment]
In approach 1 you restart libreoffice all the time. The entire point unoconv is to keep libreoffice open, so you do not have the startup overhead.

**Comment by regebro** [comment]
@osamagithub80 Did this answer your question?

**Comment by osamagithub80** [comment]
Not exactly, good point by @strichter which state the difference between approach 1 and 2. But then, is relying on Unoconv sufficient or CollaboraOnline is better? and why?

**Comment by regebro** [comment]
CollaboraOnline is an online Office Suite. Unoconv is a tool that helps you use LibreOffice to convert documents. I don't see how they are comparable.

**Comment by osamagithub80** [comment]
Converting documents is also provided by LibreOffice online through CollaboraOffice

**Comment by regebro** [comment]
Does it have a command line interface?

**Comment by osamagithub80** [comment]
I haven't tried it yet. I just wanted to know the right option to go to so that I don't waste time going into the wrong direction.

**Comment by regebro** [comment]
If you are converting a few documents manually, you don't need unoconv.

If you are converting large batches of documents, or you need to have a conversion server, then it's useful (although check out the new unoserver rewrite). I can't find any information on how to do that with CollaboraOffice Online, I'm not sure it's even possible.

**Comment by regebro** [comment]
Closed due to lack of response.
