### ISSUE TITLE
PDFs created by certain applications not suitable for redaction

### ISSUE THREAD

**Issue by mackhankins** [unoconv/unoconv#577]
I'm not sure when or what changed, but now if I convert a .doc to .pdf I can't redact some of it.  Any way to fix?  We commonly convert large batches of files to .pdf via shell and sometimes we need to redact the info.

**Comment by regebro** [comment]
Can you redact the same document if you open it with Libreoffice and export it as PDF?
If not, then this is a Libreoffice issue, not a unoconv issue.

**Comment by regebro** [comment]
Closed due to lack of response.
