### ISSUE TITLE
Error executing find_uno.py

### ISSUE THREAD

**Issue by Andres-Chandia** [unoconv/unoconv#581]
Ubuntu 16.04.6 LTS (Xenial Xerus)

python3 find_uno.py 
  File "find_uno.py", line 56
    print(f"Trying python found at {python}", end="...")
                                           ^
SyntaxError: invalid syntax

**Comment by regebro** [comment]
Your Python 3 version is too old. You need Python 3.6 or later. Python 3.5 and earlier are no longer supported.
