### ISSUE TITLE
PDF RestrictPermissions without a password?

### ISSUE THREAD

**Issue by eaxebxrbp** [unoconv/unoconv#583]
Hi,

I am using Unoconv 0.9.0 and I am wondering if it's possible to secure a PDF file's editing options **without** a password?
Here is the command I am currently using:

`unoconv -f pdf -e RestrictPermissions=true -e PermissionPassword=njc092c0283-e Printing=0 -e Changes=0 -e EnableCopyingOfContent=false <file path>`

Thanks,

**Comment by regebro** [comment]
Unoconv only sends -e flags to LibreOffice, it doesn't do anything with them, so this is a LibreOffice question.
