### ISSUE TITLE
Python 3.9.2 - Streams

### ISSUE THREAD

**Issue by kirilkirkov** [unoconv/unoconv#605]
is it possible to use with streams?

const unoconv = spawn("unoconv", ["-f", "docx", "--stdin", "--stdout"]); ?

I get errors:

.. TypeError: Expected bytes object or ByteSequence, got <class 'str'> instead.

**Comment by regebro** [comment]
Python 3 will default to treating stdin and stdout as str, so that is likely how you will have to handle it.

**Comment by kirilkirkov** [comment]
@regebro 
Can you give some simple example?

**Comment by regebro** [comment]
I don't know how you are using it, why, or where that spawn function comes from, so I can't help you there.

**Comment by kirilkirkov** [comment]
@regebro  I am using nodejs, the idea is to read the stream from google bucket and then to write it there. Currently with spawn i am calling the unoconv and i pass the streams, but i got the above error. Did you mean that with Python3 i need to convert the stream type before passing it?

**Comment by regebro** [comment]
I don't know anything about either nodejs or Google buckets, so I can't help you there. I guess using files isn't an option?
