### ISSUE TITLE
Problem converting cyrillic .doc OR .odt file to .txt

### ISSUE THREAD

**Issue by Yuseinov** [unoconv/unoconv#73]
OS: Linux Ubuntu 10.04
Unconv version: 0.3-6

When converting file with cyrillic text to txt format output is with broken encoding.
Input text:

```
Здравейте. Как сте?
This is how we do...
```

Ouput text:

```
?????????. ??? ????
This is how we do...
```

When converting from .odt OR .doc to .pdf everything is ok, but when converting to .txt then instead of text have question marks.

**Comment by RsD0p9BK** [comment]
**I'm trying to convert cyrillic.rtf to  unicode.rtf with command:**

`unoconv -f rtf -i FilterOptions=,,34 -e FilterOptions=,,76 -o '~/unicode.rtf' '~/cyrillic.rtf'`
- on mac (**local**) files converted normally without filters
- on ubuntu (**remote**) text looks the same as in source (ÞÌÒÍÅÈ Þ ÌÒÞÌÒÍÅÈ ÍÅÈ)

**remote:**
```
unoconv 0.7
platform posix/linux
python 3.4.3 (default, Nov 17 2016, 01:08:31)
[GCC 4.8.4]
LibreOffice 5.3.2.2
```
  
**local:**
```
unoconv 0.7
platform posix/darwin
python 2.7.10 (default, Feb  6 2017, 23:53:20)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
OpenOffice 4.1.3
```
