### ISSUE TITLE
Create a plugin/extension framework for document manipulations

### ISSUE THREAD

**Issue by dagwieers** [unoconv/unoconv#84]
We often get very specific feature requests from expert users that are hard to implement in generic ways. For this I think it could be useful to allow users to run one or more plugins/extensions between the import and the export phase.

Possible extensions could do one or more of the following manipulations:
- search-and-replace content
- metadata changes
- content or encoding changes
- adding/manipulating fields (#193)
- export selections (#34 and #51)
- page (dimension, orientation) changes (#32 and #116 )
- style, paragraph, character changes
- complete reformatting
- adding indexes, headers, footers
- removing images (#83)
- add encryption (#48)
- disabling comments, merging/hiding/showing changes (issue #40)
   - disabling/enabling options

The benefit of this is that users are no longer limited to the existing functionality and hopefully some of those contributed extensions that _do_ have a more generic use can be integrated as options, while specialized use-cases can be shared among users.

**Comment by MadMind** [comment]
Is it possible to take headers, footers, page background from ott ?
