### ISSUE TITLE
error-messages are inconsistently delivered on stdout or stderr, and inconsistently formatted

### ISSUE THREAD

**Issue by mvdejong** [unoconv/unoconv#94]
Platform : CentOS 5 in an Oracle VirtualBox on Windows 7.
Downloaded the 0.6 tarball on Sep 28th.

This message appears on stdout :
1. using "--export=FilterOptions=..."

unoconv: option --export must not have an argument., try `unoconv -h' for a list of all the options.

These messages appear on stderr :
1. calling unoconv without a input-file specified

unoconv: you have to provide a filename as argument
Try `unoconv -h' for more information
1. trying "--export FilterOptions=...", with a space instead of a "=" after the "--export :

Warning: Option  can not be parsed, ignoring
unoconv: file `FilterOptions=...' does not exist.
UNO IllegalArgument during import phase:
Source file cannot be read.  URL seems to be an unsupported one.

Suggestions :
- Any warning- or error-message belongs on stderr, on stdout it will be merged with the results if the "--stdout" option is used, and wreak havoc in post-processing, which will be difficult to trace if the post-processing is done via a pipeline instead of an intermediate file.
- The suggestion to use the "-h" option is on the same line in case 1, but on a separate line in case 2.
- In case 3 there is a "Warning:" without the name of the program, but the errors just report the program, not "Error" or something like that.
- In case 3 it seems that unoconv, in spite of detecting the missing input, still tries to hand over processing to the listener (this might be to handle multiple input-files ?).

**Comment by dagwieers** [comment]
I think we fixed two issues mentioned here in the master branch.

 - For some reason nobody noticed that --export was missing from the list of options, even when it was documented as such. This commit fixed it: 3c20d6ec49a97c24cfb1fe9fd61ac80944819088
 - When --stdout is provided, all extra stdout output is diverted to stderr. You can see this in commit: https://github.com/dagwieers/unoconv/commit/8a12f56a4243049e6e82098187249e608cb982e0?diff=unified#diff-0f8f2d5732364629d55c45a403e76f42R925

There is indeed some more work to do in standardizing the Info, Warning, Error and Fatal output.
