### ISSUE TITLE
unoconv fails to converts some parts of an ods doc

### ISSUE THREAD

**Issue by kertechs** [unoconv/unoconv#97]
Hi, 

We run an ubuntu 12.01 server with LibreOffice 3.5.4 and unoconv 0.4
We have a listening instance of libreoffice launched with : 
nohup soffice -headless -invisible '-accept=socket,host=localhost,port=8100;urp;' &

We need to convert some documents from ods to pdf but sometimes it fails on some values/cells only of some documents

Steps to reproduce:
1. download the source spreasheet at http://www.bennouna.net/document.ods 
2. convert it to pdf with unoconv (/usr/bin/unoconv -vvv -c "socket,host=localhost,port=8100;urp;StarOffice.ComponentContext" -f pdf /tmp/transtel/documents/2095-1352873730/document.ods on our server)
3. You'll see some "#value" on the pdf that do not exist on the ods

Thank you in advance
Best regards

Nassim Bennouna

**Comment by dagwieers** [comment]
This problem seems to be fixed since LibreOffice 4.1, however a recent commit eba79bf57e57d13cf732b2298f1831998f71b1bc breaks it again when recalculating cells.

I reverted the commit, but we may have to report this upstream again :-(
